<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/melanissimo/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/

$labels = array();

$labels['Send Melanissimo title'] = "Envoi Mélanissimo";
$labels['Send Melanissimo text'] = "La taille du message est trop importante pour un envoi par messagerie. Utiliser les services Mélanissimo pour l'envoi?";
$labels['Send Melanissimo keep the file'] = "Conserver les fichiers : ";
$labels['Send Melanissimo days'] = "jours";
$labels['cancel'] = "Annuler";
$labels['send_melanissimo'] = "Envoyer";
$labels['Over size Melanissimo error'] = "La taille totale des pièces jointes ne doit pas dépasser %%max_melanissimo_size%% octets (vous êtes à %%size%% octets)";
$labels['Send Melanissimo message'] = "Envoi du message au service Mélanissimo...";
$labels['Download files Melanissimo message'] = "Téléchargement des fichiers vers Mélanissimo...";
$labels['Melanissimo service down'] = "Le service Mélanissimo n'est pas accessible mais votre message dépasse la taille autorisé par la messagerie Mélanie2, essayez de vous connecter directement à Mélanissimo.";
$labels['Send Melanissimo error'] = "Une erreur s'est produite, impossible d'envoyer le message";
$labels['Send Melanissimo success'] = "Le message vient d'être envoyé via Mélanissimo";
$labels['action connection'] = "Connexion au service Mélanissimo";
$labels['action message'] = "Téléchargement du message sur le service Mélanissimo";
$labels['action fichier'] = "Envoi du fichier %%filename%% au service Mélanissimo";
$labels['action envoi'] = "Envoi du message";
$labels['action garde'] = "Enregistrement de la durée de garde";
$labels['pref_max_attachments_size'] = "Taille maximum des pièces jointes avant un envoi par Mélanissimo";
