<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/mel_notification/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels = [];

$labels['rizomo'] = 'Outils SNAP';
$labels['rizomo_procedure'] = 'Pour récupérer votre token "Rizomo" permettant de connecter les outils SNAP avec le Bnum : Connectez vous à %url, cliquez sur votre nom puis "Profil" enfin en bas de la page dans la section "Récupérer le token d\'accès" cliquez sur le bouton "Récupérer le token" puis collez le dans le champ ci-dessous.';
$labels['user_token'] = 'Token d\'accès Rizomo';