<?php
$labels = array();
$labels['task'] = 'Portail Web';
$labels['title'] = 'Portail Web des applications du MTES';

$labels['manageresourcesportail'] = "Liste des applications dans le portail Mél";
$labels['resourcesportail'] = "Applications";

$labels['type'] = "Type";
$labels['url'] = "Lien";

$labels['communication'] = "Communication";
$labels['stockage'] = "Stockage";
$labels['webconf'] = "Web conférence";
$labels['fluxrss'] = "Flux RSS";
$labels['sondage'] = "Sondage";
$labels['website'] = "Site web";

$labels['applications_list'] = "Liste d'applications";