<?php
$labels = array();
$labels['task'] = 'Accueil';
$labels['title'] = 'Page d\'accueil de Mél web';

$labels['manageresourcesportail'] = "Liste des vignettes dans le portail ETN";
$labels['applications_list'] = "Liste des vignettes";
$labels['resourcesportail'] = "Vignettes";
$labels['add_resource'] = "Ajouter une nouvelle vignette";
$labels['delete_resource'] = "Supprimer la vignette sélectionnée";
$labels['export_resource'] = "Exporter la vignette sélectionnée";
$labels['reinit_resources'] = "Réinitialiser toutes les vignettes (remet à zéro le tri des vignettes et masque les vignettes personnelles)";
$labels['export_resources'] = "Exporter la vignette au format JSON (peut-être de la réimporter en faisant une nouvelle vignette)";
$labels['wait'] = "Chargement en cours...";

$labels['delete_confirm'] = 'Êtes-vous sûr de vouloir supprimer cette vignette du portail ETN ? La suppression est définitive.';
$labels['reinit_confirm'] = 'Êtes-vous sûr de vouloir reinitialiser la configuration des vignettes du portail ETN ? (remet à zéro le tri des vignettes et masque les vignettes personnelles)';
$labels['show_item_confirm'] = 'La vignette est bien affichée dans le portail ETN';
$labels['hide_item_confirm'] = 'La vignette est bien masquée dans le portail ETN';
$labels['sort_items_confirm'] = 'La vignette a bien été déplacée dans le portail ETN';
$labels['delete_item_confirm'] = 'La vignette a bien été supprimée du portail ETN';
$labels['reinit_items_confirm'] = 'La configuration des vignettes a bien été réinitialisée';
$labels['modify_error'] = 'Une erreur s\'est produite lors de l\'enregistrement. Essayez d\'actualiser la page et de recommencer';

$labels['true'] = "Oui";
$labels['false'] = "Non";

$labels['flip'] = "Recto-verso";
$labels['type'] = "Type";
$labels['url'] = "Lien";
$labels['feedurl'] = "Lien du flux";
$labels['fronthtml'] = "HTML du Recto";
$labels['backhtml'] = "HTML du Verso";
$labels['provenance'] = "Provenance";

$labels['communication'] = "Communication";
$labels['html_item'] = "HTML";
$labels['stockage'] = "Stockage";
$labels['webconf'] = "Web conférence";
$labels['fluxrss'] = "Flux RSS";
$labels['fluxhtml'] = "Flux HTML";
$labels['sondage'] = "Sondage";
$labels['website'] = "Vignette simple";
$labels['website_buttons'] = "Vignette avec boutons";
$labels['website_links'] = "Vignette multi-applications";
$labels['twitter'] = "Compte Twitter";
$labels['calendar_item'] = "Calendrier du jour";
$labels['mailbox_item'] = "Boite courriel";
$labels['ariane'] = "Salon de discussion";
$labels['import_item'] = "Importer une vignette";

$labels['internet'] = "Internet";
$labels['intranet'] = "Intranet";

$labels['custom logo'] = 'Logo personnalisé';
$labels['default logo'] = 'Logo par défaut';

// Edit page
$labels['New item'] = "Création d'une nouvelle vignette";

// Type
$labels['itemtype'] = "Type de vignette";
$labels['itemtype_choice'] = "Choisissez le type de vignette que vous souhaitez créer";
$labels['itemtype_choosen'] = "Type de vignette choisi : ";
$labels['item_type'] = "Type de vignette";
$labels['item_title_type'] = "Choisissez le type de vignette que vous souhaitez afficher";

// Logo
$labels['itemlogo'] = "Logo de la vignette";
$labels['itemlogo_choice'] = "Choisissez le logo que vous souhaitez afficher sur votre vignette";
$labels['itemlogo_choosen'] = "Logo choisi pour la vignette : ";
$labels['no icon'] = "Logo par défaut";
$labels['itemiconalt'] = "Logo de la vignette";
$labels['item_logo'] = "Choix du logo";
$labels['item_title_logo'] = "Sélectionnez un logo dans la liste déroulante";
$labels['item_logo_custom'] = "Lien vers un logo personnalisé";
$labels['item_title_logo_custom'] = "Vous pouvez renseigner ici un logo personnalisé qui s'affichera sur votre vignette";
$labels['item_logobg'] = "Couleur de fond";
$labels['item_title_logobg'] = "Choisissez une couleur de fond pour le logo sélectionné, vous pouvez laisser ce champ vide pour ne pas avoir de couleur de fond";

// Info
$labels['iteminfo'] = "Informations sur la vignette";
$labels['item_name'] = "Nom de la vignette";
$labels['error_name'] = "Vous devez remplir le champ : \"Nom de la vignette\"";
$labels['item_title_name'] = "Nom à afficher en haut de la vignette";
$labels['item_color'] = "Couleur de la vignette";
$labels['item_title_color'] = "Choisissez la couleur de fond de la vignette";
$labels['item_tooltip'] = "Infobulle";
$labels['item_title_tooltip'] = "Infobulle qui s'affichera lorsque la souris passera sur la vignette";
$labels['item_description'] = "Description de la vignette";
$labels['item_title_description'] = "Prévoyez une description assez courte afin qu'elle s'affiche correctement dans la vignette";
$labels['item_provenance'] = "Afficher selon la provenance";
$labels['item_title_provenance'] = "La vignette s'affichera si la connexion se fait depuis Internet, le réseau ministériel ou les deux";
$labels['item_url'] = "Lien vers le site web";
$labels['error_url'] = "Vous devez remplir le champ : \"Lien vers le site web\"";
$labels['item_title_url'] = "Saisissez l'url qui doit s'ouvrir lorsque l'on clic sur la vignette, par exemple : http://mtes.fr/1";
$labels['item_flip'] = "Vignette de type recto-verso";
$labels['item_title_flip'] = "Si la vignette est de type recto-verso, elle peut se retourner pour afficher plus d'informations";
$labels['item_width'] = "Largeur de la vignette";
$labels['item_title_flip'] = "Choisissez avec quelle largeur la vignette s'affichera dans le portail";
$labels['required_field'] = "Ce champs est obligatoire";

$labels['from all'] = "Toujours afficher";
$labels['from internet'] = "Seulement sur Internet";
$labels['from intranet'] = "Seulement sur Intranet";

$labels['normal'] = "Normale";
$labels['large'] = "Large";

$labels['default'] = "Défaut";
$labels['red'] = "Rouge";
$labels['blue'] = "Bleu";
$labels['turquoise'] = "Turquoise";
$labels['orange'] = "Orange";
$labels['purple'] = "Violet";
$labels['green'] = "Vert";
$labels['yellow'] = "Jaune";
$labels['grey'] = "Gris";

// Types
$labels['itemwebsite'] = "Configuration de la vignette site web";
$labels['itemwebsite_buttons'] = "Configuration de la vignette site web avec bouton(s)";
$labels['itemwebsite_links'] = "Configuration de la vignette multi-applications";
$labels['itemintranet'] = "Configuration de la vignette Intranet";
$labels['itemtwitter'] = "Configuration de la vignette  compte Twitter";
$labels['itemhtml_item'] = "Configuration de la vignette contenu HTML";
$labels['itemmailbox_item'] = "Configuration de la vignette boite de messagerie";
$labels['itemcalendar_item'] = "Configuration de la vignette calendrier";
$labels['itemariane'] = "Configuration de la vignette salon de discussion";
$labels['itemcommunication'] = "Configuration de la vignette communication";
$labels['itemwebconf'] = "Configuration de la vignette Webconf";
$labels['itemstockage'] = "Configuration de la vignette Stockage";
$labels['itemimport_item'] = "Importer une vignette à partir de l'export JSON";

$labels['item_intranet'] = "Choix du site Intranet à afficher";
$labels['item_title_intranet'] = "Choisissez le site Intranet que vous souhaitez afficher avec cette vignette";
$labels['item_account'] = "Compte Twitter à afficher";
$labels['item_title_account'] = "Nom du compte Twitter (ou lien vers ce compte) à afficher sur cette vignette";
$labels['item_html'] = "Code HTML à afficher";
$labels['item_title_html'] = "Permet de choisir l'affichage HTML que vous souhaitez";
$labels['item_channel'] = "Nom du canal à afficher";
$labels['item_title_channel'] = "Saisissez ici le nom du canal ou le lien ariane vers celui-ci, par exemple : #general";
$labels['item_mailbox'] = "Choix de la boite";
$labels['item_title_mailbox'] = "Sélectionnez ici la boite de reception que vous souhaitez afficher dans la vignette";
$labels['item_calendar'] = "Choix du calendrier";
$labels['item_title_mailbox'] = "Sélectionnez ici le calendrier que vous souhaitez afficher dans la vignette";
$labels['item_import'] = "Document JSON";
$labels['item_title_import'] = "Copier/coller ici le contenu du document JSON précédemment exporté";


// Boutons
$labels['item_button_website_buttons'] = "Configuration du bouton";
$labels['item_button_website_buttons_collapse'] = "Bouton";
$labels['item_button_name'] = "Nom du bouton";
$labels['error_button_name'] = "Vous devez remplir le champ : \"Nom du bouton\"";
$labels['item_title_button_name'] = "Saisissez le nom qui s'affichera sur le bouton, attention de ne pas saisir un nom trop long";
$labels['item_button_href'] = "Lien du bouton";
$labels['error_button_href'] = "Vous devez remplir le champ : \"Lien du bouton\"";
$labels['item_title_button_href'] = "Saisissez le lien qui s'ouvrira lors d'un clic sur le bouton, par exemple : http://mtes.fr/1";
$labels['item_button_title'] = "Infobulle du bouton";
$labels['item_title_button_title'] = "Infobulle qui s'affichera lorsque la souris passera sur le bouton";
$labels['item_add_button'] = "Ajouter un nouveau bouton";
$labels['item_add_button_title'] = "Cliquez-ici pour ajouter un nouveau button à votre vignette";
$labels['item_button_back'] = "Positionner ce bouton au verso";
$labels['item_title_button_back'] = "Si mis à oui, le bouton ne sera pas sur la face avant de la vignette mais au verso";
$labels['item_delete_button'] = "Enlever ce bouton";
$labels['item_delete_button_title'] = "En cliquant ici ce bouton sera définitivement supprimé de la vignette";

// Links
$labels['item_links_logobg'] = "Couleur de fond des logos";
$labels['item_title_links_logobg'] = "Choisissez ici la couleur de fond qui s'appliquera à chaque logo d'application";
$labels['item_link_website_links'] = "Configuration de l'application";
$labels['item_link_website_links_collapse'] = "Application";
$labels['item_link_logo'] = "Logo de l'application";
$labels['item_links_iconalt'] = "Logo de l'application";
$labels['item_title_link_logo'] = "Choisissez ici le logo de l'application";
$labels['item_link_show'] = "Afficher l'application";
$labels['item_title_link_show'] = "Cochez ou décochez la case pour afficher/masquer l'application dans la vignette";
$labels['item_link_name'] = "Nom de l'application";
$labels['error_link_name'] = "Vous devez remplir le champ : \"Nom de l'application\"";
$labels['item_title_link_name'] = "Saisir le nom de l'application qui apparaitra sur la vignette";
$labels['item_link_url'] = "Lien vers l'application";
$labels['error_link_url'] = "Vous devez remplir le champ : \"Lien vers l'application\"";
$labels['item_title_link_url'] = "Saisissez l'url qui doit s'ouvrir lorsque l'on clic sur l'application, par exemple : http://mtes.fr/1";
$labels['item_link_title'] = "Infobulle de l'application";
$labels['item_title_link_title'] = "Infobulle qui s'affichera lorsque la souris passera sur l'application";
$labels['item_add_link'] = "Ajouter une nouvelle application";
$labels['item_add_link_title'] = "Cliquez-ici pour ajouter une nouvelle application à votre vignette";
$labels['item_delete_link'] = "Enlever cette application";
$labels['item_delete_link_title'] = "En cliquant ici cette application sera définitivement supprimée de la vignette";

// Twitter
$labels['twitter of '] = "Twitter de ";

// Manage
$labels['You are actually in edition mode'] = "Vous êtes en mode édition des vignettes, dans ce mode vous pouvez réorganiser votre portail";
$labels['switch off edition mode'] = "Fermer le mode édition";
$labels['Hide this item'] = "Masquer cette vignette";
$labels['Clic to hide this item'] = 'Cliquez-ici pour ne plus afficher cette vignette dans votre portail';
$labels['Edit this item'] = "Modifier cette vignette";
$labels['Clic to edit this item'] = 'Cliquez-ici pour modifier les paramètres de cette vignette';

// Days list
$labels['day_0'] = 'Dimanche';
$labels['day_1'] = 'Lundi';
$labels['day_2'] = 'Mardi';
$labels['day_3'] = 'Mercredi';
$labels['day_4'] = 'Jeudi';
$labels['day_5'] = 'Vendredi';
$labels['day_6'] = 'Samedi';

// Min days list
$labels['day_min_0'] = 'Dim.';
$labels['day_min_1'] = 'Lun.';
$labels['day_min_2'] = 'Mar.';
$labels['day_min_3'] = 'Mer.';
$labels['day_min_4'] = 'Jeu.';
$labels['day_min_5'] = 'Ven.';
$labels['day_min_6'] = 'Sam.';

// Months list
$labels['month_0'] = 'Janvier';
$labels['month_1'] = 'Février';
$labels['month_2'] = 'Mars';
$labels['month_3'] = 'Avril';
$labels['month_4'] = 'Mai';
$labels['month_5'] = 'Juin';
$labels['month_6'] = 'Juillet';
$labels['month_7'] = 'Août';
$labels['month_8'] = 'Septembre';
$labels['month_9'] = 'Octobre';
$labels['month_10'] = 'Novembre';
$labels['month_11'] = 'Décembre';

// Min months list
$labels['month_min_0'] = 'jan.';
$labels['month_min_1'] = 'fév.';
$labels['month_min_2'] = 'mars';
$labels['month_min_3'] = 'avr.';
$labels['month_min_4'] = 'mai';
$labels['month_min_5'] = 'juin';
$labels['month_min_6'] = 'juil.';
$labels['month_min_7'] = 'août';
$labels['month_min_8'] = 'sep.';
$labels['month_min_9'] = 'oct.';
$labels['month_min_10'] = 'nov.';
$labels['month_min_11'] = 'déc.';