<?php
$labels = array();
$labels['task'] = 'Portail ETN';
$labels['title'] = 'Portail Environnement de Travail Numérique';

$labels['manageresourcesportail'] = "Liste des applications dans le portail Mél";
$labels['resourcesportail'] = "Applications";

$labels['true'] = "Oui";
$labels['false'] = "Non";

$labels['flip'] = "Recto-verso";
$labels['type'] = "Type";
$labels['url'] = "Lien";
$labels['feedurl'] = "Lien du flux";
$labels['fronthtml'] = "HTML du Recto";
$labels['backhtml'] = "HTML du Verso";
$labels['provenance'] = "Provenance";

$labels['communication'] = "Communication";
$labels['html_item'] = "HTML";
$labels['stockage'] = "Stockage";
$labels['webconf'] = "Web conférence";
$labels['fluxrss'] = "Flux RSS";
$labels['fluxhtml'] = "Flux HTML";
$labels['sondage'] = "Sondage";
$labels['website'] = "Vignette simple";
$labels['website_buttons'] = "Vignette avec boutons";
$labels['website_links'] = "Vignette multi-applications";
$labels['twitter'] = "Compte Twitter";
$labels['calendar_item'] = "Calendrier du jour";
$labels['mailbox_item'] = "Boite courriel";
$labels['ariane'] = "Salon de discussion";

$labels['internet'] = "Internet";
$labels['intranet'] = "Intranet";

$labels['applications_list'] = "Liste d'applications";

// Edit page
$labels['New item'] = "Création d'une nouvelle vignette";

// Type
$labels['itemtype'] = "Type de vignette";
$labels['item_type'] = "Type de vignette";
$labels['item_title_type'] = "Choisissez le type de vignette que vous souhaitez afficher";

// Logo
$labels['itemlogo'] = "Logo de la vignette";
$labels['no icon'] = "Logo par défaut";
$labels['itemiconalt'] = "Logo de la vignette";
$labels['item_logo'] = "Choix du logo";
$labels['item_title_logo'] = "Sélectionnez un logo dans la liste déroulante";
$labels['item_logobg'] = "Couleur de fond";
$labels['item_title_logobg'] = "Choisissez une couleur de fond pour le logo sélectionné";

// Info
$labels['iteminfo'] = "Informations sur la vignette";
$labels['item_name'] = "Nom de la vignette";
$labels['item_title_name'] = "Nom à afficher en haut de la vignette";
$labels['item_tooltip'] = "Infobulle";
$labels['item_title_tooltip'] = "Infobulle qui s'affichera lorsque la souris passera sur la vignette";
$labels['item_description'] = "Description de la vignette";
$labels['item_title_description'] = "Prévoyez une description assez courte afin qu'elle s'affiche correctement dans la vignette";
$labels['item_provenance'] = "Afficher selon la provenance";
$labels['item_title_provenance'] = "La vignette s'affichera si la connexion se fait depuis Internet, le réseau ministériel ou les deux";
$labels['item_url'] = "URL de la vignette";
$labels['item_title_url'] = "Saisissez l'url qui doit s'ouvrir lorsque l'on clic sur la vignette, par exemple : http://mtes.fr/1";
$labels['item_flip'] = "Vignette de type recto-verso";
$labels['item_title_flip'] = "Si la vignette est de type recto-verso, elle peut se retourner pour afficher plus d'informations";

$labels['from all'] = "Toujours afficher";
$labels['from internet'] = "Seulement sur Internet";
$labels['from intranet'] = "Seulement sur Intranet";

// Types
$labels['itemwebsite'] = "Configuration de la vignette site web";
$labels['itemwebsite_buttons'] = "Configuration de la vignette site web avec bouton(s)";
$labels['itemwebsite_links'] = "Configuration de la vignette multi sites web";
$labels['itemintranet'] = "Configuration de la vignette Intranet";
$labels['itemtwitter'] = "Configuration de la vignette  compte Twitter";
$labels['itemhtml_item'] = "Configuration de la vignette contenu HTML";
$labels['itemmailbox_item'] = "Configuration de la vignette boite de messagerie";
$labels['itemcalendar_item'] = "Configuration de la vignette calendrier";
$labels['itemariane'] = "Configuration de la vignette salon de discussion";

$labels['item_intranet'] = "Choix du site Intranet à afficher";
$labels['item_title_intranet'] = "Choisissez le site Intranet que vous souhaitez afficher avec cette vignette";
$labels['item_account'] = "Compte Twitter à afficher";
$labels['item_title_account'] = "Nom du compte Twitter (ou lien vers ce compte) à afficher sur cette vignette";
$labels['item_html'] = "Code HTML à afficher";
$labels['item_title_html'] = "Permet de choisir l'affichage HTML que vous souhaitez";
$labels['item_channel'] = "Nom du canal à afficher";
$labels['item_title_channel'] = "Saisissez ici le nom du canal ou le lien ariane vers celui-ci, par exemple : #general";
$labels['item_mailbox'] = "Choix de la boite";
$labels['item_title_mailbox'] = "Sélectionnez ici la boite de reception que vous souhaitez afficher dans la vignette";
$labels['item_calendar'] = "Choix du calendrier";
$labels['item_title_mailbox'] = "Sélectionnez ici le calendrier que vous souhaitez afficher dans la vignette";

// Boutons
$labels['item_button_website_buttons'] = "Configuration du bouton";
$labels['item_button_name'] = "Nom du bouton";
$labels['item_title_button_name'] = "Saisissez le nom qui s'affichera sur le bouton, attention de ne pas saisir un nom trop long";
$labels['item_button_href'] = "Lien du bouton";
$labels['item_title_button_href'] = "Saisissez le lien qui s'ouvrira lors d'un clic sur le bouton, par exemple : http://mtes.fr/1";
$labels['item_button_title'] = "Infobulle du bouton";
$labels['item_title_button_title'] = "Infobulle qui s'affichera lorsque la souris passera sur le bouton";
$labels['item_add_button'] = "Ajouter un nouveau bouton";
$labels['item_button_back'] = "Positionner ce bouton au verso";
$labels['item_title_button_back'] = "Si mis à oui, le bouton ne sera pas sur la face avant de la vignette mais au verso";

// Links
$labels['item_links_logobg'] = "Couleur de fond des logos";
$labels['item_title_links_logobg'] = "Choisissez ici la couleur de fond qui s'appliquera à chaque logo d'application";
$labels['item_link_website_links'] = "Configuration de l'application web";
$labels['item_link_logo'] = "Logo de l'application";
$labels['item_links_iconalt'] = "Logo de l'application";
$labels['item_title_link_logo'] = "Choisissez ici le logo de l'application";
$labels['item_link_name'] = "Nom de l'application";
$labels['item_title_link_name'] = "Saisir le nom de l'application qui apparaitra sur la vignette";
$labels['item_link_url'] = "Lien vers l'application";
$labels['item_title_link_url'] = "Saisissez l'url qui doit s'ouvrir lorsque l'on clic sur l'application, par exemple : http://mtes.fr/1";
$labels['item_link_title'] = "Infobulle de l'application";
$labels['item_title_link_title'] = "Infobulle qui s'affichera lorsque la souris passera sur l'application";
$labels['item_add_link'] = "Ajouter une nouvelle application";

// Days list
$labels['day_0'] = 'Dimanche';
$labels['day_1'] = 'Lundi';
$labels['day_2'] = 'Mardi';
$labels['day_3'] = 'Mercredi';
$labels['day_4'] = 'Jeudi';
$labels['day_5'] = 'Vendredi';
$labels['day_6'] = 'Samedi';

// Min days list
$labels['day_min_0'] = 'Dim.';
$labels['day_min_1'] = 'Lun.';
$labels['day_min_2'] = 'Mar.';
$labels['day_min_3'] = 'Mer.';
$labels['day_min_4'] = 'Jeu.';
$labels['day_min_5'] = 'Ven.';
$labels['day_min_6'] = 'Sam.';

// Months list
$labels['month_0'] = 'Janvier';
$labels['month_1'] = 'Février';
$labels['month_2'] = 'Mars';
$labels['month_3'] = 'Avril';
$labels['month_4'] = 'Mai';
$labels['month_5'] = 'Juin';
$labels['month_6'] = 'Juillet';
$labels['month_7'] = 'Août';
$labels['month_8'] = 'Septembre';
$labels['month_9'] = 'Octobre';
$labels['month_10'] = 'Novembre';
$labels['month_11'] = 'Décembre';

// Min months list
$labels['month_min_0'] = 'jan.';
$labels['month_min_1'] = 'fév.';
$labels['month_min_2'] = 'mars';
$labels['month_min_3'] = 'avr.';
$labels['month_min_4'] = 'mai';
$labels['month_min_5'] = 'juin';
$labels['month_min_6'] = 'juil.';
$labels['month_min_7'] = 'août';
$labels['month_min_8'] = 'sep.';
$labels['month_min_9'] = 'oct.';
$labels['month_min_10'] = 'nov.';
$labels['month_min_11'] = 'déc.';