<?php
$labels = array();
$labels['mails'] = "Mails";
$labels["contacts"] = "Contacts";
$labels['create'] = "Créer";
$labels['support'] = "Assistance";
$labels['my_favorites'] = "Mes raccourcis";
$labels["contacts_organization"] = "Gestion des Annuaires";
$labels["last_frame_opened"] = "Revenir à";
$labels["nothing"] = "Aucun";

$labels["nextcloud_connection_error"] = "Impossible de récupérer les documents, l'authentification a échoué ou le plugin n'est pas bien configuré.";
$labels["a_worspace"] = "Un espace de travail";
$labels["a_mail"] = "Un email";
$labels["a_task"] = "Une tâche";
$labels["a_meeting"] = "Une évènement";
$labels["a_web_conf"] = "Une web-conférence";
$labels["a_document"] = "Un document";
$labels["a_wordpad"] = "Un bloc-note";
$labels["a_survey"] = "Un sondage Pégase";

$labels["what_do_you_want_create"] = "Que souhaitez-vous créer ?";
$labels["choose_type_doc"] = "Choisissez le type de document :";
$labels["document_folder"] = "Dossier du nouveau document";
$labels["document_name"] = "Nom du nouveau document :";
$labels["create_doc"] = "Créer un document";

$labels["text_document"] = "Document texte";
$labels["text_office_document"] = "Document office";
$labels["worksheet"] = "Feuille de calcul";
$labels["presentation"] = "Présentation";

$labels["new_n"] = "Nouveau";
$labels["new_f"] = "Nouvelle";

$labels["new_event"] = "Nouvel évènement";

$labels['roleorganizer'] = 'Organisateur';
$labels['rolerequired'] = 'Requis';
$labels['roleoptional'] = 'Optionnel';
$labels['rolechair'] = 'Présidence';
$labels['rolenonparticipant'] = 'Absent';

$labels['audioinput'] = 'Micro';
$labels['audiooutput'] = 'Audio';
$labels['videoinput'] = 'Caméra';

$labels["fullscreen"] = "Afficher la discussion instantanée en plein écran";
$labels["anchor"] = "Ancrer la discussion instantanée à droite";
$labels["close"] = "Fermer la discussion instantanée";

$labels["create_help"] = "Ouvre la fenêtre de création (email, espaces de travail, etc...)";
$labels["help_help"] = "Ouvre la fenêtre d'aide";
$labels["shortcuts_help"] = "Affiche les raccourcis";
$labels["user_help"] = "Permet de se déconnecter ou d'accéder aux options de compte";
$labels["ariane_help"] = "Ouvre la fenêtre de discussion instantanée";
$labels["webconf_enter_help"] = "Ouvre la visioconférence";
$labels["webconf_close_help"] = "Ferme et ouvre la dernière page ouverte";

$labels["webconf_hangup_help"] = "Met fin à la visioconférence";
$labels["webconf_copy_help"] = "Copie le lien de la visioconférence";
$labels["webconf_share_screen_help"] = "Commence ou termine un partage d'écran";
$labels["webconf_nextcloud_help"] = "Ouvre ou ferme la fenêtre des documents partagés";
$labels["webconf_rocket_chat_help"] = "Ouvre ou ferme la discussion instantanée";
$labels["webconf_mic_help"] = "Active ou désactive le micro";
$labels["webconf_vid_help"] = "Active ou désactive la caméra";
$labels["webconf_tile_help"] = "Active ou désactive le mode de vue \"Tuile\"";
$labels["webconf_round_help"] = "Affiche ou cache la barre d'outil";