<?php
$labels = array();
$labels['...'] = "...";
$labels['mails'] = "Mails";
$labels['mail'] = $labels['mails'];
$labels["contacts"] = "Contacts";
$labels["contact"] = $labels["contacts"];
$labels['create'] = "Créer";
$labels['support'] = "Aide";
$labels['my_favorites'] = "Mes raccourcis";
$labels["contacts_organization"] = "Gestion des Annuaires";
$labels["last_frame_opened"] = "Revenir à";
$labels["nothing"] = "Aucun";
$labels["empty_nothing"] = "Rien";
$labels['tchap'] = 'Tchap';

$labels["nextcloud_connection_error"] = "Impossible de récupérer les documents, l'authentification a échoué ou le plugin n'est pas bien configuré.";
$labels["a_worspace"] = "Un espace de travail";
$labels["a_mail"] = "Un email";
$labels["a_task"] = "Une tâche";
$labels["a_meeting"] = "Un évènement";
$labels["a_web_conf"] = "Une web-conférence";
$labels["a_document"] = "Un document";
$labels["a_wordpad"] = "Une note";
$labels["a_survey"] = "Un sondage Pégase";


$labels["h_general"] = "Aide générale";
$labels["h_video"] = "Voir les vidéos";
$labels["h_suggestion"] = "Proposer une amélioration";
$labels["h_current"] = "Aide de la page";

$labels["assistance"] = $labels['support'];
$labels["describe_your_need_in_few_words"] = 'Décrivez-nous votre besoin en quelques mots pour que l\'on puisse vous aider';
$labels["search_a_video"] = 'Rechercher une vidéo';

$labels["what_do_you_want_create"] = "Que souhaitez-vous créer ?";
$labels["choose_type_doc"] = "Choisissez le type de document :";
$labels["document_folder"] = "Dossier du nouveau document";
$labels["document_name"] = "Nom du nouveau document :";
$labels["create_doc"] = "Créer un document";
$labels['create_event'] = 'Créer un évènement';

$labels["text_document"] = "Document texte";
$labels["text_office_document"] = "Document office";
$labels["worksheet"] = "Feuille de calcul";
$labels["presentation"] = "Présentation";

$labels["empty"] = "Document vide";
$labels["mtect"] = "Mtect";
$labels["mtect_mte_mer"] = "Mtect mte mer";
$labels["transport"] = "Transports";

$labels["mte_ppt_marianne"] = "MTE";
$labels["mtect_ppt_marianne"] = "MTECT";
$labels["secmer_ppt_marianne"] = "SECMER";
$labels["mct_presentation_arial_16_9"] = "MCT présentation arial 16/9";

$labels["new_n"] = "Nouveau";
$labels["new_f"] = "Nouvelle";

$labels["new_event"] = "Nouvel évènement";

$labels['roleorganizer'] = 'Organisateur';
$labels['rolerequired'] = 'Requis';
$labels['roleoptional'] = 'Optionnel';
$labels['rolechair'] = 'Présidence';
$labels['rolenonparticipant'] = 'Absent';

$labels['audioinput'] = 'Micro';
$labels['audiooutput'] = 'Audio';
$labels['videoinput'] = 'Caméra';

$labels["fullscreen"] = "Afficher la discussion instantanée en plein écran";
$labels["anchor"] = "Ancrer la discussion instantanée à droite";
$labels["close"] = "Fermer la discussion instantanée";

$labels["close_modal"] = "Fermer la modale";

$labels["create_help"] = "Ouvre la fenêtre de création (email, espaces de travail, etc...)";
$labels["help_help"] = "Ouvre la fenêtre d'aide";
$labels["shortcuts_help"] = "Affiche les raccourcis";
$labels["welcome"] = "Bienvenue";
$labels["user_help"] = "Options de compte";
$labels["ariane_help"] = "Ouvre la fenêtre de discussion instantanée";
$labels["webconf_enter_help"] = "Ouvre la visioconférence";
$labels["webconf_close_help"] = "Ferme et ouvre la dernière page ouverte";

$labels["webconf_hangup_help"] = "Met fin à la visioconférence";
$labels["webconf_copy_help"] = "Copie le lien de la visioconférence";
$labels["webconf_share_screen_help"] = "Commence ou termine un partage d'écran";
$labels["webconf_nextcloud_help"] = "Ouvre ou ferme la fenêtre des documents partagés";
$labels["webconf_rocket_chat_help"] = "Ouvre ou ferme la discussion instantanée";
$labels["webconf_mic_help"] = "Active ou désactive le micro";
$labels["webconf_vid_help"] = "Active ou désactive la caméra";
$labels["webconf_tile_help"] = "Active ou désactive le mode de vue \"Tuile\"";
$labels["webconf_round_help"] = "Affiche ou cache la barre d'outil";
$labels["webconf_participate_help"] = "Lever/baisser la main";

$labels["saloon"] = "Salon";
$labels["webconf_saloon_name_error"] = "Le nom du salon doit faire au moins 10 caractères avec au moins 3 chiffres. Alphanumérique seulement.";
$labels["webconf_saloon_name_error_small"] = 'Le nom du salon doit faire au moins 10 caractères !';
$labels["webconf_saloon_incorrect_format_number"] = 'Il doit y avoir au moins 3 chiffres dans le nom du salon !';
$labels["webconf_saloon_incorrect_format"] = 'Alphanumérique seulement !';
$labels["attach_to"] = "Rattacher à";
$labels["a_workspace"] = "un espace de travail";
$labels["choose"] = "Choisissez";
$labels["an_ariane_space"] = "un salon Ariane";
$labels["enter"] = "Entrer";

$labels["documents"] = "Documents";
$labels["ariane"] = "Discussion";
$labels["hangup"] = "Raccrocher";
$labels["diffuse"] = "Partager";
$labels["mosaik"] = "Mosaïque";
$labels["url"] = "Url";

$labels["required_fields"] = "Champs obligatoires";
$labels["event_name"] = "Ajoutez un titre";
$labels["date_choice"] = "Choix de la période";
$labels["event_start"] = "Début de l'évènement";
$labels["event_end"] = "Fin de l'évènement";
$labels["reccurence"] = "Récurrence";
$labels["never"] = "jamais";
$labels["norecc"] = "pas de récurrence";
$labels["DAILY"] = "quotidienne";
$labels["WEEKLY"] = "hebdomadaire";
$labels["MONTHLY"] = "mensuelle";
$labels["YEARLY"] = "annuelle";
$labels["alert"] = "Alerte";
$labels["event_mode"] = "Mode d'évènement";
$labels["face_to_face"] = "En présentiel";
$labels["by_visio"] = "Par visioconférence";
$labels["by_audio"] = "Par audio";
$labels["choose_location"] = "Choisir un lieu";
$labels["choose_visio_tool"] = "Choisir l'outil de visioconférence";

$labels["state_tool_conf"] = "Webconférence de l'état";
$labels["other_tool_conf"] = "Un autre outil de visioconférence";
$labels["a_niche"] = "un créneau";
$labels["reserve"] = "Réserver";
$labels["audio_phone"] = "Téléphone de l'audio";
$labels["audio_num"] = "Numéro de l'audio";
$labels["add_file"] = "Ajouter une pièce jointe";
$labels["day_order"] = "Ordre du jour";

$labels["attach_the_event_to"] = "Rattacher l'évènement à";
$labels["choose_calendar"] = "Choisissez un agenda";
$labels["choose_event_state"] = "Choisissez le statut de l'évènement";
$labels["choose_sensivity"] = "Choisissez la sensibilité de l'évènement";
$labels["attach_to_workspace_or_category"] = "Lier à un espace de travail ou une catégorie";

$labels["continue"] = "Continuer";
$labels["add_all_member_from_a_workspace"] = "Ajouter tous les membres de l'espace de travail";
$labels["add_all"] = "Ajouter tous les membres de l'espace";
$labels["select_attendees"] = "Sélectionner les participants";
$labels["back"] = "Retour";
$labels['create_modal_back'] = 'Retour à la modale de création';
$labels["save_event"] = "Sauvegarder l'évènement";

$labels["worskpace_name"] = "Nom de l'espace de travail";
$labels["choose_avatar"] = "Sélectionner un avatar";
$labels["import_picture"] = "Importer une photo";
$labels["description"] = "Description";
$labels["choose_hashtag"] = "Sélectionner une thématique";
$labels["define_end_date"] = "Définir une date de fin";

$labels["authorized_access"] = "Autoriser l'accès";
$labels["restricted"] = "Restreint";
$labels["public"] = "Public";
$labels["color"] = "Couleur";
$labels["define_end_date"] = "Définir une date de fin";
$labels["select_attendees2"] = "Sélectionner des participants";

$labels["attendees_list"] = "Liste des participants";

$labels["menu_create_help_workspace"] = "Créer un nouvel espace de travail";
$labels["menu_create_help_email"] = "Ouvre la fenêtre de création d'un e-mail";
$labels["menu_create_help_event"] = "Créer un nouvel évènement";
$labels["menu_create_help_webconf"] = "Créer une webconférence qui sera ouverte dans le WebMel";
$labels["menu_create_help_task"] = "Créer une nouvelle tâche";
$labels["menu_create_help_doc"] = "Créer un nouveau document";
$labels["menu_create_help_note"] = "Créer une nouvelle note";
$labels["menu_create_help_survey"] = "Créer un nouveau sondage";

$labels["menu_assistance_helppage_general"] = "Aide générale";
$labels["menu_assistance_helppage_video"] = "Voir les vidéos";
$labels["menu_assistance_helppage_suggestion"] = "Proposer une amélioration";
$labels["menu_assistance_helppage_current"] = "Aide de la page";

$labels["change_avatar"] = "Changer d'avatar";

$labels["last_day"] = "Jour précédent";
$labels["next_day"] = "Jour suivant";

$labels["my_apps"] = "Plus d'applications";

$labels["normal"] = "Normal";
$labels["smaller"] = "Plus petit";
$labels["larger"] = "Plus grand";
$labels["yes"] = "Oui";
$labels["no"] = "Non";
$labels["up"] = "En haut";
$labels["down"] = "En bas";

$labels["mel-icon-size"] = "Mail - Taille des icônes en tête";
$labels["mel-icon-size-nomail"] = "Taille des icônes en tête";
$labels["mel-folder-space"] = "Mail - Espacement des dossiers";
$labels["mel-folder-space-nomail"] = "Espacement des dossiers";
$labels["mel-message-space"] = "Mail - Espacement des messages";
$labels["mel-message-space-nomail"] = "Espacement des messages";
$labels["mel-chat-placement"] = "Placement de la bulle";
$labels["mel-calendar-space"] = "Espacement des agendas";
$labels["mel-folder-grouping"] = "Regroupement des dossiers";

$labels["hide_bubble"] = "Cacher la bulle de discussion";
$labels["show_bubble"] = "Afficher la bulle de discussion";
$labels["all-day"] = "Journée entière";

$labels["without_spaces"] = "Sans espaces";
$labels["refresh"] = "Rafraîchir la page en cours";

$labels["bckg"] = "Arrière-plan";
$labels["webconf_bckg_help"] = "Utiliser une image comme arrière-plan.";

$labels["more"] = "Plus";
$labels["toggle_chat"] = "Afficher/Fermer le chat interne";
$labels["webconf_tile_help_old"] = "Affiche ou ferme le chat qui sert à communiquer avec les personnes externe au BNum";
$labels["change_theme"] = "Changer de thème";
$labels["back_to_notifications"] = "Retour aux notifications";

$labels["event-compose"] = "Ecrire aux participants";
$labels["event-self-invitation"] = "S'inviter";
$labels["duplicate"] = "Dupliquer";
$labels["copy_w_p"] = "Copier sans les participants";

$labels["force-refresh"] = "Recharger et actualiser les dossiers";
$labels["new-mail-from"] = "Nouveau message aux mêmes destinataires";

$labels['calendar'] = 'Agenda';

$labels['globalsearch'] = 'Rechercher un mail, un contact, une réunion';
$labels['search_mail_max'] = 'Nombre de résultats max depuis les mails';
$labels['search_on_all_bal'] = 'Rechercher dans toutes les boîtes partagées ?';
$labels['search_on_all_bali_folders'] = 'Rechercher dans tous les sous dossiers de la bali ?';
$labels['balp'] = 'Boîte partagée';
$labels['search-in-this-balp'] = 'Rechercher dans cette boîte ?';
$labels['search-in-this-folder'] = 'Rechercher dans ce dossier ?';

$labels['main_nav'] = 'Navigation principale';
$labels['secondary_nav'] = 'Navigation Secondaire';
$labels['main_contents'] = 'Contenu principal';

$labels['to_search'] = 'Rechercher';
$labels['notifications_help'] = 'Afficher les notifications';
$labels['settings_help'] = 'Afficher les options';
$labels['global_search_title'] = 'Recherche globale : recherche dans les contacts, les mails ainsi que l\'agenda.';

$labels['open_chat_popup'] = 'Ouvrir la discussion instantanée';
$labels['other_actions'] = 'Autres actions';
$labels['avatars'] = 'Avatars';
$labels['open_create_popup'] = 'Ouvrir la popup de création';
$labels['create_things'] = 'Création';
$labels['filter_by'] = 'Filtrer par';
$labels['content_type'] = 'Type de contenu';
$labels['mel_box'] = 'Boîte';
$labels['all_mel_boxes'] = 'Toutes';
$labels['results_for'] = 'résultats pour';
$labels['order_by'] = 'Trier par';
$labels['desc'] = 'Le plus récent';
$labels['asc'] = 'Le plus ancien';
$labels['hide_chat_popup_button'] = 'Bulle de discussion instantanée';
$labels['to_participate'] = 'Participer';

$labels['title_needed'] = 'Vous devez mettre un titre !';
$labels['startdate_needed'] = 'Vous devez mettre une date de début !';
$labels['enddate_needed'] = 'Vous devez mettre une date de fin !';
$labels['bad_format_date'] = 'Vous devez mettre une date au format jj/MM/yyyy HH:mm !';

$labels['add_user_button_title'] = 'Ajoute le participant saisi dans le champ précédent.';
$labels['add_user_to_event'] = 'Ajouter un participant'; 
$labels['add_user_to_event_title'] = "Saisissez le nom de l'utilisateur pour afficher l'autocomplétion ou saisissez une adresse email puis cliquez sur 'Ajouter'";

$labels['no_events_today'] = "Pas de réunion aujourd'hui !";
$labels['no_events_this_day'] = 'Pas de réunion à cette date !';

$labels['webconf_already_running'] = "Une visioconférence est déja en cours, finissez celle en cours avant d'en démarrer une nouvelle !";
$labels['see_plus'] = 'Voir plus';
$labels['see_minus'] = 'Voir moins';

$labels['note_created_success'] = 'Note créée avec succès !';
$labels['note_reinit_success'] = 'Note réinitialisée avec succès !';
$labels['note_deleted_success'] = 'Note supprimée avec succès !';
$labels['note_move_success'] = 'Notes déplacées avec succès !';

$labels['settings'] = 'Paramètres';

$labels['change_background_color'] = 'Changer la couleur de fond';
$labels['change_text_color'] = 'Changer la couleur du texte';

$labels['quit_settings'] = 'Quitter les paramètres';

$labels['move'] = 'Déplacer';
$labels['move_up'] = 'Déplacer en haut';
$labels['move_down'] = 'Déplacer en bas';

$labels['search_settings'] = 'Paramètres de la recherche';

$labels['webconf_toggle_participantspane_help'] = "Ouvrir ou fermer la boîte des participants";
$labels['toggle_participantspane'] = 'Participants';
$labels['save_model'] = 'Modèle';
$labels['save_model_title'] = 'Sauvegarder comme un nouveau modèle';
$labels['is_model'] = 'Ce message est un modèle';
$labels['use'] = 'Utiliser';
$labels['model_saved'] = 'Modèle enregistré avec succès !';
$labels['itipaccepted'] = 'Accepté';
$labels['statusneeds-action'] = 'En attente';
$labels['webconf_toggle_chat_help'] = "Affiche ou ferme le tchat interne";
$labels['webconf_phone_help'] = "Copie le numéro de téléphone pour permettre à d'autre de rejoindre la visio en cours";
$labels['webconf_phone'] = "Rejoindre par téléphone";
$labels['visio'] = 'Visioconférences';
$labels['chat'] = 'Discussions';

$labels['visio_ask_on_end'] = 'Afficher le questionnaire satisfaction ?';
$labels['visio_audio_parameters'] = 'Affichage des options micro et vidéo';
$labels['chat_startup'] = 'Connexion automatique au démarrage ?';

$labels['mel-scrollbar-size'] = 'Taille de la barre de défilement';
$labels['default'] = 'Défaut';
$labels['auto'] = 'Automatique (test)';
$labels['compact'] = "Compact";
$labels['large'] = 'Large';

$labels['tab_title_style'] = "Affichage des notifications de la navigation pricipale sur l'onglet en cours";

$labels['notif-all'] = "Somme des notifications";
$labels['notif-page'] = "Notifications de la page en cours";
$labels['notif-nothing'] = "Rien/Fonctionnement par défaut";

$labels['tab_title_style_help'] = "\"<all/>\" affiche sur l'onglet la somme des notifications sur la navigation principal (ex : 5 mail, 3 évènements => (8) Paramètres)\r\n\"<page/>\" affiche seulement les notifications de la page en cours (ex : (3) Agenda).\r\nFonctionnement par défaut sinon.";

$labels['app_chat'] = 'Discussions';
$labels['app_documents'] = 'Documents';
$labels['app_tasks'] = 'Tâches';
$labels['app_news'] = 'M\'informer';
$labels['app_ul'] = 'Liens utiles';
$labels['app_kanban'] = 'Kanban';
$labels['app_survey'] = 'Sondage';
$labels['app_rizomo'] = 'Suite numérique';
$labels['app_calendar'] = 'Agenda';
$labels['app_workspace'] = 'Espaces de travail';
$labels['app_parapheur'] = 'Parapheur';

$labels['to_comment'] = 'Commenter';

$labels['experimental'] = 'Expérimental';
$labels['param-note-in-my-day'] = 'Activer les notes dans ma journée ?';
$labels['param-reorder-notes'] = 'Réordonner vos notes ?';

$labels['toggle_mp'] = 'Envoyer un message privé';
$labels['webconf_toggle_mp_help'] = 'Envoyer un message privé à quelqu\'un';

$labels['visio_password_manager'] = 'Gestion du mot de passe';
$labels['password'] = 'Mot de passe';
$labels['password_visio_error'] = 'Vous devez mettre un mot de passe !';
$labels['delete_password'] = 'Supprimer le mot de passe';
$labels['visio_locked'] = 'La visioconférence a été vérouiller par le mot de passe : <password/>';
$labels['visio_unlocked'] = 'La visioconférence a été dévérouiller !';

$labels['custom_calendar_notification_option'] = 'Notif.';
$labels['custom_calendar_notification_ok_desc'] = "L'utilisateur sera notifié par mail.";
$labels['custom_calendar_notification_nok_desc'] = "L'utilisateur ne sera pas notifié par mail.";

$labels['mel_logo_desc'] = "Ministères Transition Écologique, Cohésion des Territoires, Mer - Liberté, Égalité, Fraternité";
$labels['param-show-back-icon'] = 'Afficher le bouton "Revenir à" ?';

$labels["custom_taskbar"] = "Personnaliser";
$labels['sended_folder'] = 'Dossier des mails envoyés';

$labels['ok'] = 'Disponible';
$labels['nothere'] = 'Absent';
$labels['busy'] = 'Ne pas déranger';
$labels['logout'] = 'Hors ligne';
$labels['custom_status'] = 'Statut personnalisé...';
$labels['change_status'] = 'Modifier le statut';
$labels['delay'] = 'Retard d\'envoi (secondes)';
$labels['delay_speed'] = 'Retard d\'envoi';
$labels['delay_setting_help'] = "Retarde l'envoi du message de x secondes pour pouvoir annuler l'envoi de celui-ci.";
$labels['quitdelayconfirmation'] = 'Si vous quittez, le mail ne sera pas envoyé, êtes-vous sûr de vouloir quitter ?';
$labels['delaytimer'] = 'Le message sera envoyé dans';
$labels['new-note'] = 'Nouvelle note';
$labels['note-create-title'] = $labels['new-note'].' - Créer une nouvelle note qui s\'affichera après les autres notes';
$labels['main_nav_can_deploy'] = 'Déplier la barre de navigation au survol ?';

$labels['attention'] = 'Attention';
$labels['leaving_bnum'] = 'Vous êtes sur le point de quitter le Bnum pour aller sur le site suivant :';
$labels['always_authorize'] = 'Toujours autoriser les liens provenant de ';
$labels['warning_suspect_url'] = ' est référencé comme risque potentiel de phishing. Je reconnais que je ne donnerai pas mes identifiants Bnum.';
$labels['warning_external_link'] = 'Attention, ne jamais donner vos identifiants ou mots de passe Bnum ou Mél sur le site que vous allez visiter';
$labels['open_external_link'] = 'Visiter le site';

$labels['informations'] = 'Informations';
$labels['double_authentication'] = 'Authentification';
$labels['download_application'] = 'Télécharger l\'application';
$labels['double_authentication_notification'] = 'Configurez l\'authentification à deux facteurs pour sécuriser votre accès au Bnum';
$labels['introduction_text'] = 'À partir de %%date%%, un renforcement de la sécurité de votre compte deviendra obligatoire pour accéder au Bnum.';
$labels['secondary_email_text'] = 'Pour pouvoir récupérer votre code au cas où vous perdez votre téléphone par exemple, veuillez entrer une adresse e-mail de récupération :';
$labels['different_email'] = 'L\'email de récupération doit être distinct de l\'email professionnel.';
$labels['verification_email_text'] = 'Saisissez le code de vérification reçu par mail';
$labels['verification_application_text'] = 'Rentrer le code de validation affiché sur l’application';
$labels['application_text'] = 'Télécharger une application de l\'authentification à deux facteurs comme <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=fr&gl=US" target="_blank">Google Authenticator</a> ou <a href="https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp&hl=fr&gl=US" target="_blank">FreeOTP Authenticator</a>.';
$labels['scan_authentication_code'] = 'Vous pouvez maintenant scanner ce QR Code pour enregistrer le bnum dans votre application.';
$labels['code_step_after'] = 'Après avoir installé l\'application, vous pourrez scanner le code de l\'étape suivante pour enregistrer le bnum dans votre application.';
$labels['add_key'] = 'Ou ajouter cette clé dans votre application :';
$labels['download_app'] = 'Télécharger l\'application';
$labels['show_me'] = 'Configurer maintenant';
$labels['later'] = 'Plus tard';
$labels['close_double_auth'] = 'Fermer';
$labels['double_authentication_validation'] = 'L’authentification à deux facteurs à correctement été configuré !';
$labels['send_code'] = 'Envoyer le code';
$labels['email_format_error'] = 'Le format de l\'adresse mail n\'est pas valide';
$labels['code_expired'] = 'Le code à expiré';
$labels['wrong_code'] = 'Le code est erroné';
$labels['error'] = 'Erreur';
$labels['doubleauth-error'] = 'Erreur lors de la configuration de l\'authentification double facteur';
$labels['doubleauth_not_activated'] = 'L\'authentification à deux facteurs n\'a pas été activée';
$labels['enter_code'] = 'Merci de rentrer un code valide';
$labels['send_email_error'] = 'Erreur serveur lors de l\'envoi du mail';

$labels['introduction_text_without_date'] = 'Nous allons commencer à configurer le renforcement de la sécurité sur votre compte. Cliquez sur "'.$labels['show_me'] .'" pour continuer !';
$labels['set-to-favorite'] = 'Ajouter aux favoris';
$labels['unset-to-favorite'] = 'Retirer des favoris';
$labels['disable-animations'] = 'Désactiver les animations';
$labels['disable-animations-helper'] = "Désactive les animation du thème en cours pour améliorer les performances.";
$labels['cancel-color-folder'] = 'Restaurer la couleur par défaut';
$labels['update-color-folder'] = 'Changer la couleur du dossier';
$labels['update-icon-folder'] = "Changer l'icône du dossier";

$labels['app_tchap'] = "Tchap";
$labels['tchap'] = "Tchap";
$labels['tchap_options'] = "Ouvrir les paramètres de Tchap";
$labels['tchap_disconnect'] = "Se déconnecter de Tchap";
$labels['tchap_sidebar'] = "Afficher la barre latérale de Tchap";
$labels['event-location-visio'] = "En visioconférence";
$labels['event-location-location'] = "En présentiel";
$labels['event-location-audio'] = "Par audio";
$labels['event-visio-internal'] = "Webconférence de l'État";
$labels['event-visio-external'] = "Webconférence externe";

$labels['week'] = 'semaine';
$labels['week_plurial'] = $labels['week'].'s';
$labels['week_after'] = ' et %0 jour';
$labels['week_after_plurial'] = $labels['week_after'].'s';

$labels['day'] = 'jour';
$labels['day_plurial'] = $labels['day'].'s';
$labels['day_after'] = ' et %0 heure';
$labels['day_after_plurial'] = $labels['day_after'].'s';

$labels['hour'] = 'heure';
$labels['hour_plurial'] = $labels['hour'].'s';
$labels['hour_after'] = ' et %0 minute';
$labels['hour_after_plurial'] = $labels['hour_after'].'s';

$labels['minute'] = 'minute';
$labels['minute_plurial'] = $labels['minute'].'s';
$labels['minute_after'] = ' et %0 seconde';
$labels['minute_after_plurial'] = $labels['minute_after'].'s';

$labels['rappel_of'] = 'Rappel de %0 avant';
$labels['no_rappel'] = 'Aucun rappel';
$labels['custom_alarm_title'] = 'Alarme personnalisée';
$labels['validate'] = 'Valider';

$labels['invalid_guests'] = 'Impossible d\'ajouter certains participants !';
$labels['existing_guest'] = 'Le participant %0 éxiste déjà !';

$labels['add_guests'] = 'Ajoutez des participants';
$labels['req_guest'] = 'Participants obligatoires';

$labels['error_empty_event_visio_room'] = 'Le nom de la visioconférence ne doit être vide !';
$labels['error_too_small_event_visio_room'] = 'Le nom de la visioconférence doit avoir au moins 10 charactères !';
$labels['error_less_number_event_visio_room'] = 'Le nom de la visioconférence doit avoir au moins 3 chiffres !';
$labels['unknown_error'] = 'Erruer inconnue !';
$labels['error_empty_event_audio'] = 'Le numéro de téléphone ne doit être vide !';

$labels['found_audio_date'] = 'Réserver une audio-conférence';
$labels['add'] = 'Ajouter';
$labels['delete'] = 'Supprimer';

$labels['external_user_name'] = "Utilisateur externe au Bnum";
$labels['external_user_title'] = "Cet utilisateur n'a pas encore été créé dans le Bnum. À la création de l'espace, il recevra un courriel pour initialiser son compte.";
$labels['pad'] = 'Pad';

$labels['login_da'] = "Si vous êtes sur internet et n'avez pas activé l'authentification à double facteur vous ne pouvez pas vous connecter.<br/>Vous devez passer par le VPN pour vous connecter et ainsi activer l'authentification à deux facteurs";
