<?php
$labels = array();
$labels['...'] = "...";
$labels['mails'] = "Mails";
$labels['mail'] = $labels['mails'];
$labels["contacts"] = "Contacts";
$labels["contact"] = $labels["contacts"];
$labels['create'] = "Créer";
$labels['support'] = "Assistance";
$labels['my_favorites'] = "Mes raccourcis";
$labels["contacts_organization"] = "Gestion des Annuaires";
$labels["last_frame_opened"] = "Revenir à";
$labels["nothing"] = "Aucun";
$labels["empty_nothing"] = "Rien";

$labels["nextcloud_connection_error"] = "Impossible de récupérer les documents, l'authentification a échoué ou le plugin n'est pas bien configuré.";
$labels["a_worspace"] = "Un espace de travail";
$labels["a_mail"] = "Un email";
$labels["a_task"] = "Une tâche";
$labels["a_meeting"] = "Un évènement";
$labels["a_web_conf"] = "Une web-conférence";
$labels["a_document"] = "Un document";
$labels["a_wordpad"] = "Une note";
$labels["a_survey"] = "Un sondage Pégase";

$labels["h_general"] = "Aide générale";
$labels["h_video"] = "Voir les vidéos";
$labels["h_suggestion"] = "Proposer une amélioration";
$labels["h_current"] = "Aide de la page";

$labels["assistance"] = "Assistance";
$labels["describe_your_need_in_few_words"] = 'Décrivez-nous votre besoin en quelques mots pour que l\'on puisse vous aider';
$labels["search_a_video"] = 'Rechercher une vidéo';

$labels["what_do_you_want_create"] = "Que souhaitez-vous créer ?";
$labels["choose_type_doc"] = "Choisissez le type de document :";
$labels["document_folder"] = "Dossier du nouveau document";
$labels["document_name"] = "Nom du nouveau document :";
$labels["create_doc"] = "Créer un document";
$labels['create_event'] = 'Créer un évènement';

$labels["text_document"] = "Document texte";
$labels["text_office_document"] = "Document office";
$labels["worksheet"] = "Feuille de calcul";
$labels["presentation"] = "Présentation";

$labels["new_n"] = "Nouveau";
$labels["new_f"] = "Nouvelle";

$labels["new_event"] = "Nouvel évènement";

$labels['roleorganizer'] = 'Organisateur';
$labels['rolerequired'] = 'Requis';
$labels['roleoptional'] = 'Optionnel';
$labels['rolechair'] = 'Présidence';
$labels['rolenonparticipant'] = 'Absent';

$labels['audioinput'] = 'Micro';
$labels['audiooutput'] = 'Audio';
$labels['videoinput'] = 'Caméra';

$labels["fullscreen"] = "Afficher la discussion instantanée en plein écran";
$labels["anchor"] = "Ancrer la discussion instantanée à droite";
$labels["close"] = "Fermer la discussion instantanée";

$labels["close_modal"] = "Fermer la modale";

$labels["create_help"] = "Ouvre la fenêtre de création (email, espaces de travail, etc...)";
$labels["help_help"] = "Ouvre la fenêtre d'aide";
$labels["shortcuts_help"] = "Affiche les raccourcis";
$labels["welcome"] = "Bienvenue";
$labels["user_help"] = "Bienvenue ! - Options de compte";
$labels["ariane_help"] = "Ouvre la fenêtre de discussion instantanée";
$labels["webconf_enter_help"] = "Ouvre la visioconférence";
$labels["webconf_close_help"] = "Ferme et ouvre la dernière page ouverte";

$labels["webconf_hangup_help"] = "Met fin à la visioconférence";
$labels["webconf_copy_help"] = "Copie le lien de la visioconférence";
$labels["webconf_share_screen_help"] = "Commence ou termine un partage d'écran";
$labels["webconf_nextcloud_help"] = "Ouvre ou ferme la fenêtre des documents partagés";
$labels["webconf_rocket_chat_help"] = "Ouvre ou ferme la discussion instantanée";
$labels["webconf_mic_help"] = "Active ou désactive le micro";
$labels["webconf_vid_help"] = "Active ou désactive la caméra";
$labels["webconf_tile_help"] = "Active ou désactive le mode de vue \"Tuile\"";
$labels["webconf_round_help"] = "Affiche ou cache la barre d'outil";

$labels["saloon"] = "Salon";
$labels["webconf_saloon_name_error"] = "Le nom du salon doit faire au moins 10 caractères avec au moins 3 chiffres. Alphanumérique seulement.";
$labels["webconf_saloon_name_error_small"] = 'Le nom du salon doit faire au moins 10 caractères !';
$labels["webconf_saloon_incorrect_format_number"] = 'Il doit y avoir au moins 3 chiffres dans le nom du salon !';
$labels["webconf_saloon_incorrect_format"] = 'Alphanumérique seulement !';
$labels["attach_to"] = "Rattacher à";
$labels["a_workspace"] = "un espace de travail";
$labels["choose"] = "Choisissez";
$labels["an_ariane_space"] = "un salon Ariane";
$labels["enter"] = "Entrer";

$labels["documents"] = "Documents";
$labels["ariane"] = "Discussion";
$labels["hangup"] = "Raccrocher";
$labels["diffuse"] = "Partager";
$labels["mosaik"] = "Mosaïque";
$labels["url"] = "Url";

$labels["required_fields"] = "Champs obligatoires";
$labels["event_name"] = "Nom de l'évènement";
$labels["date_choice"] = "Choix de la période";
$labels["event_start"] = "Début de l'évènement";
$labels["event_end"] = "Fin de l'évènement";
$labels["reccurence"] = "Récurrence";
$labels["never"] = "jamais";
$labels["DAILY"] = "quotidienne";
$labels["WEEKLY"] = "hebdomadaire";
$labels["MONTHLY"] = "mensuelle";
$labels["YEARLY"] = "annuelle";
$labels["alert"] = "Alerte";
$labels["event_mode"] = "Mode d'évènement";
$labels["face_to_face"] = "En présentiel";
$labels["by_visio"] = "Par visioconférence";
$labels["by_audio"] = "Par audio";
$labels["choose_location"] = "Choisir un lieu";
$labels["choose_visio_tool"] = "Choisir l'outil de visioconférence";

$labels["state_tool_conf"] = "Webconférence de l'état";
$labels["other_tool_conf"] = "Un autre outil de visioconférence";
$labels["a_niche"] = "un créneau";
$labels["reserve"] = "Réserver";
$labels["audio_phone"] = "Téléphone de l'audio";
$labels["audio_num"] = "Numéro de l'audio";
$labels["add_file"] = "Ajouter une pièce jointe";
$labels["day_order"] = "Ordre du jour";

$labels["attach_the_event_to"] = "Rattacher l'évènement à";
$labels["choose_calendar"] = "Choisissez un calendrier";
$labels["choose_event_state"] = "Choisissez le statut de l'évènement";
$labels["choose_sensivity"] = "Choisissez la sensibilité de l'évènement";

$labels["continue"] = "Continuer";
$labels["add_all_member_from_a_workspace"] = "Ajouter tous les membres de l'espace de travail";
$labels["add_all"] = "Ajouter tous les membres de l'espace";
$labels["select_attendees"] = "Sélectionner les participants";
$labels["back"] = "Retour";
$labels['create_modal_back'] = 'Retour à la modale de création';
$labels["save_event"] = "Sauvegarder l'évènement";

$labels["worskpace_name"] = "Nom de l'espace de travail";
$labels["choose_avatar"] = "Sélectionner un avatar";
$labels["import_picture"] = "Importer une photo";
$labels["description"] = "Description";
$labels["choose_hashtag"] = "Sélectionner une thématique";
$labels["define_end_date"] = "Définir une date de fin";

$labels["authorized_access"] = "Autoriser l'accès";
$labels["restricted"] = "Restreint";
$labels["public"] = "Public";
$labels["color"] = "Couleur";
$labels["define_end_date"] = "Définir une date de fin";
$labels["select_attendees2"] = "Sélectionner des participants";

$labels["attendees_list"] = "Liste des participants";

$labels["menu_create_help_workspace"] = "Créer un nouvel espace de travail";
$labels["menu_create_help_email"] = "Ouvre la fenêtre de création d'un e-mail";
$labels["menu_create_help_event"] = "Créer un nouvel évènement";
$labels["menu_create_help_webconf"] = "Créer une webconférence qui sera ouverte dans le WebMel";
$labels["menu_create_help_task"] = "Créer une nouvelle tâche";
$labels["menu_create_help_doc"] = "Créer un nouveau document";
$labels["menu_create_help_note"] = "Créer une nouvelle note";
$labels["menu_create_help_survey"] = "Créer un nouveau sondage";

$labels["menu_assistance_helppage_general"] = "Aide générale";
$labels["menu_assistance_helppage_video"] = "Voir les vidéos";
$labels["menu_assistance_helppage_suggestion"] = "Proposer une amélioration";
$labels["menu_assistance_helppage_current"] = "Aide de la page";

$labels["change_avatar"] = "Changer d'avatar";

$labels["last_day"] = "Jour précédent";
$labels["next_day"] = "Jour suivant";

$labels["my_apps"] = "Plus d'applications";

$labels["normal"] = "Normal";
$labels["smaller"] = "Plus petit";
$labels["larger"] = "Plus grand";
$labels["yes"] = "Oui";
$labels["no"] = "Non";
$labels["up"] = "En haut";
$labels["down"] = "En bas";

$labels["mel-icon-size"] = "Mail - Taille des icônes en tête";
$labels["mel-folder-space"] = "Mail - Espacement des dossiers";
$labels["mel-message-space"] = "Mail - Espacement des messages";
$labels["mel-chat-placement"] = "Chat - Placement de la bulle";
$labels["mel-calendar-space"] = "Espacement des agendas";

$labels["hide_bubble"] = "Cacher la bulle de discussion";
$labels["show_bubble"] = "Afficher la bulle de discussion";
$labels["all-day"] = "Journée entière";

$labels["without_spaces"] = "Sans espaces";
$labels["refresh"] = "Rafraîchir la page en cours";

$labels["bckg"] = "Arrière-plan";
$labels["webconf_bckg_help"] = "Utiliser une image comme arrière-plan.";

$labels["more"] = "Plus";
$labels["toggle_chat"] = "Afficher/Fermer le chat interne";
$labels["webconf_tile_help"] = "Affiche ou ferme le chat qui sert à communiquer avec les personnes externe au BNum";
$labels["change_theme"] = "Changer de thème";

$labels["event-compose"] = "Ecrire aux participants";
$labels["event-self-invitation"] = "S'inviter";
$labels["duplicate"] = "Dupliquer";
$labels["copy_w_p"] = "Copier sans les participants";

$labels["force-refresh"] = "Recharger et actualiser les dossiers";
$labels["new-mail-from"] = "Nouveau message aux mêmes destinataires";

$labels['calendar'] = 'Agenda';

$labels['globalsearch'] = 'Recherche globale';
$labels['search_mail_max'] = 'Nombre de résultats max depuis les mails';
$labels['search_on_all_bal'] = 'Rechercher dans toutes les boîtes partagées ?';
$labels['search_on_all_bali_folders'] = 'Rechercher dans tous les sous dossiers de la bali ?';
$labels['balp'] = 'Boîte partagée';
$labels['search-in-this-balp'] = 'Rechercher dans cette boîte ?';
$labels['search-in-this-folder'] = 'Rechercher dans ce dossier ?';

$labels['main_nav'] = 'Navigation principale';
$labels['secondary_nav'] = 'Navigation Secondaire';
$labels['main_contents'] = 'Contenu principal';

$labels['to_search'] = 'Rechercher';
$labels['global_search_title'] = 'Recherche globale : recherche dans les contacts, les mails ansi que l\'agenda.';

$labels['open_chat_popup'] = 'Ouvrir la discussion instantanée';
$labels['other_actions'] = 'Autres actions';
$labels['avatars'] = 'Avatars';
$labels['open_create_popup'] = 'Ouvrir la popup de création';
$labels['create_things'] = 'Création';
$labels['filter_by'] = 'Filtrer par';
$labels['content_type'] = 'Type de contenu';
$labels['mel_box'] = 'Boîte';
$labels['all_mel_boxes'] = 'Toutes';
$labels['results_for'] = 'résultats pour';
$labels['order_by'] = 'Trier par';
$labels['desc'] = 'Le plus récent';
$labels['asc'] = 'Le plus ancien';
$labels['hide_chat_popup_button'] = 'Cacher la bulle de discussion instantée';
$labels['to_participate'] = 'Participer';

$labels['title_needed'] = 'Vous devez mettre un titre !';
$labels['startdate_needed'] = 'Vous devez mettre une date de début !';
$labels['enddate_needed'] = 'Vous devez mettre une date de fin !';
$labels['bad_format_date'] = 'Vous devez mettre une date au format jj/MM/yyyy HH:mm !';

$labels['add_user_button_title'] = 'Ajoute le participant saisi dans le champ précédent.';
$labels['add_user_to_event'] = 'Ajouter un participant'; 
$labels['add_user_to_event_title'] = "Saisissez le nom de l'utilisateur pour afficher l'autocomplétion ou saisissez une adresse email puis cliquez sur 'Ajouter'";

$labels['no_events_today'] = "Pas de réunion aujourd'hui !";
$labels['no_events_this_day'] = 'Pas de réunion à cette date !';

$labels['webconf_already_running'] = "Une visioconférence est déja en cours, finissez celle en cours avant d'en démarrer une nouvelle !";
$labels['see_plus'] = 'Voir plus';

$labels['note_created_success'] = 'Note créée avec succès !';
$labels['note_reinit_success'] = 'Note réinitialisée avec succès !';
$labels['note_deleted_success'] = 'Note supprimée avec succès !';
$labels['note_move_success'] = 'Notes déplacées avec succès !';

$labels['settings'] = 'Paramètres';

$labels['change_background_color'] = 'Changer la couleur de fond';
$labels['change_text_color'] = 'Changer la couleur du texte';

$labels['quit_settings'] = 'Quitter les paramètres';

$labels['move_up'] = 'Déplacer en haut';
$labels['move_down'] = 'Déplacer en bas';

$labels['search_settings'] = 'Paramètres de la recherche';