<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/moncompte/skins/mi_larry/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/

$labels = array();

$labels['changepasswordmiom'] = 'Mot de passe MCE';
$labels['changepasswordmiom_goto'] = 'Accéder au changement du mot de passe';
$labels['changepasswordmiom_error'] = 'Erreur $code => $message';
$labels['changepasswordmiom_error500'] = 'Erreur interne du serveur';
$labels['changepasswordmiom_canotchange'] = "Vous n'avez pas le droit de modifier votre mot de passe";
$labels['changepasswordmiom_notfound_mi_auth'] = "Impossible de trouver les paraètres du plugin mi_auth";
$labels['changepasswordmiom_email_adress'] = "Votre adresse mail : ";