<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/mel_notification/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels = [];

$labels['notifications'] = 'Notifications';
$labels['Notifications'] = 'Mes notifications';
$labels['Notification modification...'] = 'Mise à jour de la notification...';
$labels['Notification deleting...'] = 'Suppression de la notification...';
$labels['Unread notification'] = 'Une notification non lue';
$labels['X unread notifications'] = '%d notifications non lues';
$labels['now'] = 'maintenant';
$labels['X minutes ago'] = 'il y a %d min';
$labels['X hours ago'] = 'il y a %d h';
$labels['last day'] = '%s à %h';
$labels['Mark as read'] = ' ';
$labels['Mark as read title'] = 'Cliquez ici pour passer cette notification en lue';
$labels['Mark as unread'] = ' ';
$labels['Mark as unread title'] = 'Cliquez ici pour passer cette notification en non lue';
$labels['Delete'] = ' ';
$labels['Delete title'] = 'Cliquez ici pour supprimer la notification';
$labels['Action'] = 'Ouvrir';
$labels['Action title'] = 'Cliquez ici pour ouvrir le lien de la notification';
$labels['sun'] = 'Dim';
$labels['mon'] = 'Lun';
$labels['tue'] = 'Mar';
$labels['wed'] = 'Mer';
$labels['thu'] = 'Jeu';
$labels['fri'] = 'Ven';
$labels['sat'] = 'Sam';
$labels['all'] = 'Toutes';
$labels['Manage notifications'] = 'Gérer les notifications';
$labels['Manage notifications title'] = 'Gérer le fonctionnement des notifications';
$labels['Delete all'] = 'Supprimer';
$labels['Delete all confirm'] = 'Êtes-vous sûr de vouloir supprimer toutes les notifications affichées ?';
$labels['Delete all title'] = 'Supprimer toutes les notifications, si un filtre est activé, seules les notifications filtrées seront supprimées';
$labels['Mark all as read'] = 'Passer en lu';
$labels['Mark all as read title'] = 'Passer toutes les notifications en lues, si un filtre est activé, seules les notifications filtrées seront passées en lues';
$labels['No notification'] = "Pas de notification";
$labels['No notification for'] = "Pas de notification pour \"%s\"";
$labels['New message'] = "Nouveau courriel";