<?php
$labels = array();
$labels['title'] = 'Page d\'assistance de Mél';
$labels['what do you want ?'] = 'Que souhaitez-vous faire ?';
$labels['describe your need in few words'] = 'Décrivez-nous votre besoin en quelques mots pour que l\'on puisse vous aider (service en bêta)';
$labels['product news'] = 'Les nouveautés de Mél web';
$labels['help page'] = 'Voir l\'aide générale de Mél';
$labels['help current page'] = 'Voir l\'aide de la page courante';
$labels['help no result'] = 'Vous ne trouvez pas ce que vous cherchez ? Vous pouvez contacter votre cellule informatique ou nous poser la question dans le salon de discussion instantanée dédiée à Mél';
$labels['help no result channel'] = 'Ouvrir le salon de discussion';
$labels['help no result support'] = 'Contacter votre cellule informatique';
$labels['make a suggestion'] = 'Proposer une amélioration';
$labels['help search no result'] = 'Pas de résultat, essayez de saisir plus de mots clés (ex: agenda, partager, signature, ...).';
$labels['help search open'] = 'Ouvrir l\'aide';