<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Εργασίες';
$labels['list'] = 'Λίστα εργασιών';
$labels['tags'] = 'Ετικέτες';
$labels['export'] = 'Εξαγωγή';
$labels['exporttitle'] = 'Εξαγωγή σε iCalendar';
$labels['currentview'] = 'τρέχουσα προβολή';
$labels['searchterms'] = 'Όροι αναζήτησης';
$labels['removelist'] = 'Αφαίρεση από την λίστα';
$labels['newtask'] = 'Νέα εργασία';
$labels['createfrommail'] = 'Αποθήκευση ως εργασία';
$labels['printtitle'] = 'Εκτύπωση εργασιών';
$labels['edit'] = 'Επεξεργασία';
$labels['delete'] = 'Διαγραφή';
$labels['title'] = 'Τίτλος';
$labels['description'] = 'Περιγραφή';
$labels['start'] = 'Έναρξη';
$labels['starttime'] = 'Ώρα έναρξης';
$labels['repeat'] = 'Επανάληψη';
$labels['status'] = 'Κατάσταση';
$labels['status-completed'] = 'Ολοκληρώθηκε';
$labels['created'] = 'Δημιουργήθηκε';
$labels['changed'] = 'Τελευταία τροποποίηση';
$labels['today'] = 'Σήμερα';
$labels['tomorrow'] = 'Αύριο';
$labels['removetag'] = 'Αφαίρεση';
$labels['newtask'] = 'Νέα εργασία';
$labels['save'] = 'Αποθήκευση';
$labels['cancel'] = 'Άκυρο';
$labels['tabsummary'] = 'Περίληψη';
$labels['listname'] = 'Όνομα';
$labels['yes'] = 'ναι';
$labels['savingdata'] = 'Αποθήκευση δεδομένων...';
$labels['role'] = 'Ρόλος';
$labels['availability'] = 'Διαθ.';
$labels['confirmstate'] = 'Κατάσταση';
$labels['roleorganizer'] = 'Οργανωτής';
$labels['taskhistory'] = 'Ιστορικό';
$labels['objectchangelog'] = 'Αλλαγή ιστορικού';
$labels['comment'] = 'Σχόλιο';
$labels['rsvpcomment'] = 'Σχόλιο';
