<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['export'] = 'Eksportēt';
$labels['exporttitle'] = 'Eksportēt uz iCalendar';
$labels['exportattachments'] = 'Ar pielikumiem';
$labels['tasklistsubscribe'] = 'Rādīt sarakstā vienmēr';
$labels['searchterms'] = 'Meklēšanas nosacījumi';
$labels['removelist'] = 'Dzēst no saraksta';
$labels['printdescriptions'] = 'Drukāt aprakstus';
$labels['edit'] = 'Labot';
$labels['description'] = 'Apraksts';
$labels['start'] = 'Sākums';
$labels['starttime'] = 'Sākums';
$labels['alarms'] = 'Atgādinājums';
$labels['repeat'] = 'Atkārtot';
$labels['links'] = 'Atsauce';
$labels['status'] = 'Statuss';
$labels['status-needs-action'] = 'Nepieciešama darbība';
$labels['status-in-process'] = 'Procesā';
$labels['status-completed'] = 'Pabeigts';
$labels['status-cancelled'] = 'Atcelts';
$labels['created'] = 'Izveidots';
$labels['changed'] = 'Mainīts';
$labels['taskoptions'] = 'iespējas';
$labels['all'] = 'Visi';
$labels['today'] = 'Šodien';
$labels['tomorrow'] = 'Rīt';
$labels['removelink'] = 'Noņemt atsauci uz e-pastu';
$labels['save'] = 'Saglabāt';
$labels['cancel'] = 'Atcelt';
$labels['tabsummary'] = 'Kopsavilkums';
$labels['tabrecurrence'] = 'Atkārtojums';
$labels['tabattachments'] = 'Pielikumi';
$labels['tabsharing'] = 'Dalīšanās';
$labels['listname'] = 'Nosaukums';
$labels['showalarms'] = 'Rādīt atgādinājumus';
$labels['at'] = ' ';
$labels['yes'] = 'jā';
$labels['savingdata'] = 'Saglabājam...';
$labels['role'] = 'Loma';
$labels['availability'] = 'Pieej.';
$labels['confirmstate'] = 'Statuss';
$labels['roleorganizer'] = 'Organizētājs';
$labels['rolerequired'] = 'Obligāti';
$labels['roleoptional'] = 'Pēc izvēles';
$labels['rolechair'] = 'Vadītājs';
$labels['sendinvitations'] = 'Nosūtīt uzaicinājumus';
$labels['itipupdatesubject'] = '"$title" ir mainīts';
$labels['itipcancelsubject'] = '"$title" ir atcelts';
$labels['taskhistory'] = 'Vēsture';
$labels['objectchangelog'] = 'Mainīt vēsturi';
$labels['objectdiff'] = 'Izmaiņas no $rev1 uz $rev2';
$labels['objectdiffnotavailable'] = 'Izvēlētās versijas nav salīdzināmas';
$labels['objectrestoresuccess'] = 'Versija $rev veiksmīgi atjaunota';
$labels['objectrestoreerror'] = 'Kļūda atjaunojot veco versiju';
$labels['itipcomment'] = 'Uzaicinājumam/paziņojuma komentārs';
$labels['andnmore'] = 'vēl $nr ...';
$labels['comment'] = 'Komentārs';
$labels['rsvpcomment'] = 'Komentārs';
$labels['importerror'] = 'Kļūda importa laikā';
$labels['attendeupdateesuccess'] = 'Dalībnieku statusi veiksmīgi atjaunoti';
$labels['itipinvalidrequest'] = 'Šis uzaicinājums vairs nav spēkā';
