<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/moncompte/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/

$labels = array();

$labels['next_events'] = 'Évènements à venir';
$labels['today'] = 'Aujourd\'hui';
$labels['today_min'] = 'auj.';
$labels['tomorrow'] = 'Demain';
$labels['yesterday'] = 'Hier';
$labels['yesterday_min'] = 'hier';
$labels['previous'] = 'Précédent';
$labels['next'] = 'Suivant';
$labels['event_title'] = 'Cliquez-ici pour ouvrir votre calendrier';
$labels['no_event'] = 'Aucun évènement à venir';
$labels['no_event_title'] = 'Pas d\'évènement à venir';
$labels['new_event'] = 'Nouvel évènement';
$labels['new_event_title'] = 'Cliquez-ici pour créer un nouvel évènement';
$labels['contactphoto'] = 'Photo du contact';
$labels['allday'] = 'Journée';
$labels['allday_min'] = 'Jour';
$labels['mail'] = 'COURRIEL';
$labels['im'] = 'DISCUSSION';
$labels['task'] = 'TACHE';
$labels['event'] = 'AGENDA';
$labels['date'] = '%%day%% à %%hour%%';
$labels['you'] = 'Vous';
$labels['contacts_count_title'] = 'Nouveaux Messages';
$labels['contacts_favorites_title'] = 'Contacts Favoris';
$labels['dismiss'] = 'Terminé';
$labels['later'] = 'Plus tard';

// Status list
$labels['away'] = 'Absent';
$labels['busy'] = 'Ne pas déranger';
$labels['online'] = 'Disponible';
$labels['offline'] = 'Invisible';
$labels['logout'] = 'Se déconnecter';
$labels['away_min'] = 'Abs.';
$labels['busy_min'] = 'Occup.';
$labels['online_min'] = 'Disp.';
$labels['offline_min'] = 'Invi.';
$labels['logout_min'] = 'Déco.';

// Days list
$labels['day_0'] = 'Dimanche';
$labels['day_1'] = 'Lundi';
$labels['day_2'] = 'Mardi';
$labels['day_3'] = 'Mercredi';
$labels['day_4'] = 'Jeudi';
$labels['day_5'] = 'Vendredi';
$labels['day_6'] = 'Samedi';

// Min days list
$labels['day_min_0'] = 'Dim.';
$labels['day_min_1'] = 'Lun.';
$labels['day_min_2'] = 'Mar.';
$labels['day_min_3'] = 'Mer.';
$labels['day_min_4'] = 'Jeu.';
$labels['day_min_5'] = 'Ven.';
$labels['day_min_6'] = 'Sam.';

// Months list
$labels['month_0'] = 'Janvier';
$labels['month_1'] = 'Février';
$labels['month_2'] = 'Mars';
$labels['month_3'] = 'Avril';
$labels['month_4'] = 'Mai';
$labels['month_5'] = 'Juin';
$labels['month_6'] = 'Juillet';
$labels['month_7'] = 'Août';
$labels['month_8'] = 'Septembre';
$labels['month_9'] = 'Octobre';
$labels['month_10'] = 'Novembre';
$labels['month_11'] = 'Décembre';

// Min months list
$labels['month_min_0'] = 'jan.';
$labels['month_min_1'] = 'fév.';
$labels['month_min_2'] = 'mars';
$labels['month_min_3'] = 'avr.';
$labels['month_min_4'] = 'mai';
$labels['month_min_5'] = 'juin';
$labels['month_min_6'] = 'juil.';
$labels['month_min_7'] = 'août';
$labels['month_min_8'] = 'sep.';
$labels['month_min_9'] = 'oct.';
$labels['month_min_10'] = 'nov.';
$labels['month_min_11'] = 'déc.';


?>
