<?php 
$labels = [];
$labels['mel_supervision'] = 'mel_supervision';
$labels['mail_warning_subject'] = '[ALERTE] Modification suspecte de l\'identité du compte $email';
$labels['mail_warning_message_reply-to'] = '"Reply to" dans "Identités et signature" à été défini sur l\'adresse externe : $key';
$labels['mail_warning_message_bcc'] = '"Cci" dans "Identités et signature" à été défini sur l\'adresse externe : $key';