<?php

/**
 * Localizations for the csv_export plugin
 *
 * Copyright (C) 2016, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/csv_export/
 */

$labels = array();
$labels['title'] = 'Contacts export';
$labels['text'] = 'Please, choose the export file format:';
$labels['csv'] = 'CSV (comma-separated)';
$labels['vcf'] = 'vCard';
$labels['format'] = 'Format';

$labels["UID"] = "UID";
$labels["Title"] = "Title";
$labels["Description"] = "Description";
$labels["Start"] = "Start";
$labels["Due"] = "Due";
$labels["Organizer Name"] = "Organizer Name";
$labels["Organizer Email"] = "Organizer Email";


$labels["Display Name"] = "Display Name";
$labels["Prefix"] = "Prefix";
$labels["First Name"] = "First Name";
$labels["Middle Name"] = "Middle Name";
$labels["Last Name"] = "Last Name";
$labels["Suffix"] = "Suffix";
$labels["Nick Name"] = "Nick Name";

$labels["Birthday"] = "Birthday";
$labels["Anniversary"] = "Anniversary";

$labels["E-mail - Home"] = "E-mail - Home";
$labels["E-mail - Work"] = "E-mail - Work";
$labels["E-mail - Other"] = "E-mail - Other";

$labels["Home Address Street"] = "Home Address Street";
$labels["Home Address City"] = "Home Address City";
$labels["Home Address Zip Code"] = "Home Address Zip Code";
$labels["Home Address Region"] = "Home Address Region";
$labels["Home Address Country"] = "Home Address Country";

$labels["Work Address Street"] = "Work Address Street";
$labels["Work Address City"] = "Work Address City";
$labels["Work Address Zip Code"] = "Work Address Zip Code";
$labels["Work Address Region"] = "Work Address Region";
$labels["Work Address Country"] = "Work Address Country";

$labels["Other Address Street"] = "Other Address Street";
$labels["Other Address City"] = "Other Address City";
$labels["Other Address Zip Code"] = "Other Address Zip Code";
$labels["Other Address Region"] = "Other Address Region";
$labels["Other Address Country"] = "Other Address Country";

$labels["Home Phone"] = "Home Phone";
$labels["Work Phone"] = "Work Phone";
$labels["Mobile Phone"] = "Mobile Phone";
$labels["Other Phone"] = "Other Phone";
$labels["Home Fax"] = "Home Fax";
$labels["Work Fax"] = "Work Fax";
$labels["Pager"] = "Pager";

$labels["Organization"] = "Organization";
$labels["Department"] = "Department";
$labels["Job Title"] = "Job Title";
$labels["Manager"] = "Manager";

$labels["Gender"] = "Gender";
$labels["Assistant"] = "Assistant";
$labels["Assistant's Phone"] = "Assistant's Phone";
$labels["Spouse"] = "Spouse";

$labels["Categories"] = "Categories";
$labels["Notes"] = "Notes";

$labels["Home Web Page"] = "Home Web Page";
$labels["Work Web Page"] = "Work Web Page";

$labels["Jabber"] = "Jabber";
$labels["Skype"] = "Skype";
$labels["MSN"] = "MSN";