<?php

/**
 * Localizations for the csv_export plugin
 *
 * Copyright (C) 2016, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/csv_export/
 */

$labels = array();
$labels['title'] = 'Export des contacts';
$labels['text'] = 'Choisissez le format d\'export:';
$labels['csv'] = 'CSV (séparé par des virgules)';
$labels['vcf'] = 'vCard';
$labels['format'] = 'Format';

$labels["UID"] = "UID";
$labels["Title"] = "Titre";
$labels["Description"] = "Description";
$labels["Start"] = "Début";
$labels["Due"] = "Fin";
$labels["Organizer Name"] = "Organisateur";
$labels["Organizer Email"] = "Organisateur E-mail";


$labels["Display Name"] = "Nom complet";
$labels["Prefix"] = "Préfixe";
$labels["First Name"] = "Prénom";
$labels["Middle Name"] = "Deuxième prénom";
$labels["Last Name"] = "Nom";
$labels["Suffix"] = "Suffixe";
$labels["Nick Name"] = "Surnom";

$labels["Birthday"] = "Anniversaire";
$labels["Anniversary"] = "Anniversaire mariage";

$labels["E-mail - Home"] = "E-mail domicile";
$labels["E-mail - Work"] = "E-mail travail";
$labels["E-mail - Other"] = "E-mail autre";

$labels["Home Address Street"] = "Adresse domicile rue";
$labels["Home Address City"] = "Adresse domicile ville";
$labels["Home Address Zip Code"] = "Adresse domicile code postal";
$labels["Home Address Region"] = "Adresse domicile région";
$labels["Home Address Country"] = "Adresse domicile pays";

$labels["Work Address Street"] = "Adresse travail rue";
$labels["Work Address City"] = "Adresse travail ville";
$labels["Work Address Zip Code"] = "Adresse travail code postal";
$labels["Work Address Region"] = "Adresse travail région";
$labels["Work Address Country"] = "Adresse travail pays";

$labels["Other Address Street"] = "Adresse autre rue";
$labels["Other Address City"] = "Adresse autre ville";
$labels["Other Address Zip Code"] = "Adresse autre code postal";
$labels["Other Address Region"] = "Adresse autre région";
$labels["Other Address Country"] = "Adresse autre pays";

$labels["Home Phone"] = "Téléphone maison";
$labels["Work Phone"] = "Téléphone travail";
$labels["Mobile Phone"] = "Mobile";
$labels["Other Phone"] = "Autre téléphone";
$labels["Home Fax"] = "Fax maison";
$labels["Work Fax"] = "Fax travail";
$labels["Pager"] = "Pager";

$labels["Organization"] = "Structure";
$labels["Department"] = "Service";
$labels["Job Title"] = "Fonction";
$labels["Manager"] = "Manageur";

$labels["Gender"] = "Genre";
$labels["Assistant"] = "Assistant";
$labels["Assistant's Phone"] = "Téléphone assistant";
$labels["Spouse"] = "Epouse";

$labels["Categories"] = "Catégories";
$labels["Notes"] = "Notes";

$labels["Home Web Page"] = "Page web domicile";
$labels["Work Web Page"] = "Page web travail";

$labels["Jabber"] = "Jabber";
$labels["Skype"] = "Skype";
$labels["MSN"] = "MSN";