<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitBnum
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\Bnum\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Bnum\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\Bnum\\AppInfo\\Application' => __DIR__ . '/..' . '/../lib/AppInfo/Application.php',
        'OCA\\Bnum\\Controller\\BnumAPIController' => __DIR__ . '/..' . '/../lib/Controller/BnumAPIController.php',
        'OCA\\Bnum\\Listener\\LoadAdditionalListener' => __DIR__ . '/..' . '/../lib/Listener/LoadAdditionalListener.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitBnum::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitBnum::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitBnum::$classMap;

        }, null, ClassLoader::class);
    }
}
