<?php
$labels = array();
$labels['my_news'] = "M'informer";
$labels['news'] = "Informations";
$labels['my_strings_of_news'] = "Mes fils d'informations";
$labels['modified'] = "Modifié le";
$labels['created'] = "Publié le";
$labels['no_news'] = "Pas d'information pour le moment.";
$labels['information'] = "Information";
$labels['Sunday'] = 'Dimanche';
$labels['Monday'] = 'Lundi';
$labels['Tuesday'] = 'Mardi';
$labels['Wednesday'] = 'Mercredi';
$labels['Thursday'] = 'Jeudi';
$labels['Friday'] = 'Vendredi';
$labels['Saturday'] = 'Samedi';

$labels['January'] = 'Janvier';
$labels['February'] = 'Février';
$labels['March'] = 'Mars';
$labels['April'] = 'Avril';
$labels['May'] = 'Mai';
$labels['June'] = 'Juin';
$labels['July'] = 'Juillet';
$labels['August'] = 'Août';
$labels['September'] = 'Septembre';
$labels['October'] = 'Octobre';
$labels['November'] = 'Novembre';
$labels['December'] = 'Décembre';

$labels['date_asc'] = "Ancien au plus récent";
$labels['date_desc'] = "Récent au plus ancien";
$labels['site'] = "Site";
$labels['source'] = "Source";

$labels['tout'] = "A la suite";
$labels['un'] = "Vignette";
$labels['news_mode'] = "Mode des news";
$labels['news_start_nb_rows'] = "Lignes d'informations par défaut";

$labels["small"] = "Petit format";
$labels["large"] = "Grand format";

$labels["right_q"] = "Administrateur et publieur";
$labels["right_a"] = "Administrateur";
$labels["right_p"] = "Publieur";