<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['compare'] = 'Compara';
$labels['objectchangelog'] = 'Historial';
$labels['revision'] = 'Revisió';
$labels['user'] = 'Usuari';
$labels['operation'] = 'Acció';
$labels['actionappend'] = 'Desat';
$labels['actionmove'] = 'Mogut';
$labels['actiondelete'] = 'Suprimit';
$labels['showrevision'] = 'Mostra aquesta versió';
$labels['restore'] = 'Restaura aquesta versió';
$labels['tabsharing'] = 'Compartit';
