<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Ukázat historii';
$labels['compare'] = 'Porovnat';
$labels['objectchangelog'] = 'Historie';
$labels['objectdiff'] = 'Změny od $rev1 do $rev2';
$labels['revision'] = 'Revize';
$labels['user'] = 'Uživatel';
$labels['operation'] = 'Činnost';
$labels['actionreceive'] = 'Přijato';
$labels['actionappend'] = 'Uloženo';
$labels['actionmove'] = 'Přesunuto';
$labels['actiondelete'] = 'Smazáno';
$labels['actionread'] = 'Označeno jako přečtené';
$labels['actionflagset'] = 'Příznak nastaven';
$labels['actionflagclear'] = 'Příznak odstraněn';
$labels['showrevision'] = 'Ukázat tuto verzi';
$labels['restore'] = 'Obnovit tuto verzi';
$labels['tabsharing'] = 'Sdílení';
