<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Vis historik';
$labels['compare'] = 'Sammenlign';
$labels['objectchangelog'] = 'Historik';
$labels['objectdiff'] = 'Ændringer fra $rev1 til $rev2';
$labels['revision'] = 'Revision';
$labels['user'] = 'Bruger';
$labels['operation'] = 'Handling';
$labels['actionreceive'] = 'Modtaget';
$labels['actionappend'] = 'Gemt';
$labels['actionmove'] = 'Flyttet';
$labels['actiondelete'] = 'Slettet';
$labels['actionread'] = 'Markér som læst';
$labels['actionflagset'] = 'Markering er angivet';
$labels['actionflagclear'] = 'Markering er fjernet';
$labels['showrevision'] = 'Vis denne version';
$labels['restore'] = 'Genskab denne version';
$labels['tabsharing'] = 'Deling';
