<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Verlauf anzeigen';
$labels['compare'] = 'Vergleichen';
$labels['objectchangelog'] = 'Verlauf';
$labels['objectdiff'] = 'Änderungen aus $rev1 nach $rev2';
$labels['revision'] = 'Version';
$labels['user'] = 'Benutzer';
$labels['operation'] = 'Aktion';
$labels['actionreceive'] = 'Empfangen';
$labels['actionappend'] = 'Gespeichert';
$labels['actionmove'] = 'Verschoben';
$labels['actiondelete'] = 'Gelöscht';
$labels['actionread'] = 'Als gelesen markiert';
$labels['actionflagset'] = 'Status gesetzt';
$labels['actionflagclear'] = 'Status entfernt';
$labels['showrevision'] = 'Diese Version anzeigen';
$labels['restore'] = 'Diese Version wiederherstellen';
$labels['tabsharing'] = 'Freigabe';
