<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Προβολή ιστορικού';
$labels['compare'] = 'Σύγκριση';
$labels['objectchangelog'] = 'Ιστορικό';
$labels['user'] = 'Χρήστης';
$labels['operation'] = 'Ενέργεια';
$labels['actionreceive'] = 'Ληφθέντα';
$labels['actionappend'] = 'Αποθηκεύτηκε';
$labels['actiondelete'] = 'Διαγραμμένα';
