<?php

/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */

$labels = array();

// history dialog
$labels['showhistory'] = 'Show History';
$labels['compare'] = 'Compare';
$labels['objectchangelog'] = 'History';
$labels['objectdiff'] = 'Changes from $rev1 to $rev2';
$labels['revision'] = 'Revision';
$labels['user'] = 'User';
$labels['operation'] = 'Action';
$labels['actionreceive'] = 'Received';
$labels['actionappend'] = 'Saved';
$labels['actionmove'] = 'Moved';
$labels['actiondelete'] = 'Deleted';
$labels['actionread'] = 'Marked as Read';
$labels['actionflagset'] = 'Flag set';
$labels['actionflagclear'] = 'Flag removed';
$labels['showrevision'] = 'Show this version';
$labels['restore'] = 'Restore this version';
$labels['objectchangelognotavailable'] = 'History is not available for this object.';
$labels['tabsharing'] = 'Sharing';
$labels['aclnorights'] = 'You do not have administrator rights for this folder.';
