<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Mostrar Historial';
$labels['compare'] = 'Comparar';
$labels['objectchangelog'] = 'Historial';
$labels['objectdiff'] = 'Cambios de $rev1 a $rev2';
$labels['revision'] = 'Revisión';
$labels['user'] = 'Usuario';
$labels['operation'] = 'Acción';
$labels['actionreceive'] = 'Recibido';
$labels['actionappend'] = 'Guardado';
$labels['actionmove'] = 'Movido';
$labels['actiondelete'] = 'Eliminado';
$labels['actionread'] = 'Marcado como Leído';
$labels['actionflagset'] = 'Marca realizada';
$labels['actionflagclear'] = 'Marca eliminada';
$labels['showrevision'] = 'Mostrar esta versión';
$labels['restore'] = 'Recuperar esta versión';
$labels['objectchangelognotavailable'] = 'El historial no está disponible para este objeto.';
$labels['tabsharing'] = 'Compartir';
$labels['aclnorights'] = 'No tiene permisos de administrador para esta carpeta.';
