<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Mostrar historial';
$labels['compare'] = 'Comparar';
$labels['objectchangelog'] = 'Historia';
$labels['objectdiff'] = 'Cambiar de $rev1 a $rev2';
$labels['revision'] = 'Revisión';
$labels['user'] = 'Usuario';
$labels['operation'] = 'Acción';
$labels['actionreceive'] = 'Recibido';
$labels['actionappend'] = 'Salvado';
$labels['actionmove'] = 'Movido';
$labels['actiondelete'] = 'Borrado';
$labels['actionread'] = 'Marcado como leído';
$labels['actionflagset'] = 'Marca establecita';
$labels['actionflagclear'] = 'Marca eliminada';
$labels['showrevision'] = 'Mostrar esta versión';
$labels['restore'] = 'Restaurar esta versión';
$labels['tabsharing'] = 'Compartir';
