<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Näita ajalugu';
$labels['compare'] = 'Võrdle';
$labels['objectchangelog'] = 'Ajalugu';
$labels['objectdiff'] = 'Muudatused versioonide $rev1 ja $rev2 vahel';
$labels['revision'] = 'Versioon';
$labels['user'] = 'Kasutaja';
$labels['operation'] = 'Toiming';
$labels['actionreceive'] = 'Saadud';
$labels['actionappend'] = 'Salvestatud';
$labels['actionmove'] = 'Liigutatud';
$labels['actiondelete'] = 'Kustutatud';
$labels['actionread'] = 'Märgitud loetuks';
$labels['actionflagset'] = 'Lisa lipp';
$labels['actionflagclear'] = 'Lipp on eemaldatud';
$labels['showrevision'] = 'Näita seda versiooni';
$labels['restore'] = 'Taasta see versioon';
$labels['objectchangelognotavailable'] = 'Selle objekti ajalugu pole saadaval.';
$labels['tabsharing'] = 'Jagamine';
$labels['aclnorights'] = 'Sul pole selles kaustas administraatori õiguseid.';
