<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Näytä historia';
$labels['compare'] = 'Vertaa';
$labels['objectchangelog'] = 'Historia';
$labels['objectdiff'] = 'Muutokset versiosta $rev1 versioon $rev2';
$labels['revision'] = 'Versio';
$labels['user'] = 'Käyttäjä';
$labels['operation'] = 'Toiminto';
$labels['actionreceive'] = 'Vastaanotettu';
$labels['actionappend'] = 'Tallennettu';
$labels['actionmove'] = 'Siirretty';
$labels['actiondelete'] = 'Poistettu';
$labels['actionread'] = 'Merkitty luetuksi';
$labels['actionflagset'] = 'Lippu asetettu';
$labels['actionflagclear'] = 'Lippu poistettu';
$labels['showrevision'] = 'Näytä tämä versio';
$labels['restore'] = 'Palauta tämä versio';
$labels['objectchangelognotavailable'] = 'Tälle objektille ei ole historiaa saatavilla.';
$labels['tabsharing'] = 'Jakaminen';
$labels['aclnorights'] = 'Sinulla ei ole ylläpitäjän oikeuksia tähän kansioon.';
