<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Montrer historique';
$labels['compare'] = 'Comparer';
$labels['objectchangelog'] = 'Historique';
$labels['objectdiff'] = 'Modifications depuis $rev1 jusqu\'à $rev2';
$labels['revision'] = 'Version';
$labels['user'] = 'Utilisateur';
$labels['operation'] = 'Action';
$labels['actionreceive'] = 'Reçu';
$labels['actionappend'] = 'Sauvegardé';
$labels['actionmove'] = 'Déplacé';
$labels['actiondelete'] = 'Supprimé';
$labels['actionread'] = 'Marqué lu';
$labels['actionflagset'] = 'Marque mise';
$labels['actionflagclear'] = 'Marque retirée';
$labels['showrevision'] = 'Afficher cette version';
$labels['restore'] = 'Restaurer cette version';
$labels['tabsharing'] = 'Partage';
