<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['compare'] = 'Confronta';
$labels['objectchangelog'] = 'Storico';
$labels['revision'] = 'Revisione';
$labels['user'] = 'Utente';
$labels['operation'] = 'Azione';
$labels['actionappend'] = 'Salvato';
$labels['actionmove'] = 'Spostato';
$labels['actiondelete'] = 'Cancellato';
$labels['showrevision'] = 'Mostra questa versione';
$labels['restore'] = 'Rirpistina questa versione';
$labels['tabsharing'] = 'Condivisione';
