<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = '履歴表示';
$labels['compare'] = '比較';
$labels['objectchangelog'] = '履歴';
$labels['objectdiff'] = '$rev1 から $rev2 への変更';
$labels['revision'] = 'リヴィジョン';
$labels['user'] = 'ユーザ';
$labels['operation'] = '行動';
$labels['actionreceive'] = '受信済';
$labels['actionappend'] = '保存済';
$labels['actionmove'] = '移動済';
$labels['actiondelete'] = '削除済';
$labels['actionread'] = '既読としてマーク';
$labels['actionflagset'] = 'フラグ設定';
$labels['actionflagclear'] = 'フラグ削除';
$labels['showrevision'] = '現在のバージョンの表示';
$labels['restore'] = 'このバージョンを復元';
$labels['tabsharing'] = '共有';
