<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Geschiedenis tonen';
$labels['compare'] = 'Vergelijken';
$labels['objectchangelog'] = 'Geschiedenis';
$labels['objectdiff'] = 'Wijzigingen van $rev1 tot $rev2';
$labels['user'] = 'Gebruiker';
$labels['actionappend'] = 'Opgeslagen';
$labels['actionmove'] = 'Verplaatst';
$labels['actiondelete'] = 'Verwijderd';
$labels['tabsharing'] = 'Delen';
