<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['compare'] = 'Porównaj';
$labels['objectchangelog'] = 'Historia';
$labels['objectdiff'] = 'Zmiany od $rev1 do $rev2';
$labels['revision'] = 'Wersja';
$labels['user'] = 'Użytkownik';
$labels['operation'] = 'Akcja';
$labels['actionappend'] = 'Zapisane';
$labels['actionmove'] = 'Przeniesione';
$labels['actiondelete'] = 'Usunięte';
$labels['showrevision'] = 'Pokaż tą wersję';
$labels['restore'] = 'Przywróć tą wersję';
$labels['tabsharing'] = 'Udostępnianie';
