<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Pokaż Historię';
$labels['compare'] = 'Porównaj';
$labels['objectchangelog'] = 'Historia';
$labels['objectdiff'] = 'Zmiany od $rev1 do $rev2';
$labels['revision'] = 'Wersja';
$labels['user'] = 'Użytkownik';
$labels['operation'] = 'Akcja';
$labels['actionreceive'] = 'Odebrany';
$labels['actionappend'] = 'Zapisane';
$labels['actionmove'] = 'Przeniesione';
$labels['actiondelete'] = 'Usunięte';
$labels['actionread'] = 'Oznaczony jako Przeczytany';
$labels['actionflagset'] = 'Flaga ustawiona';
$labels['actionflagclear'] = 'Flaga usunięta';
$labels['showrevision'] = 'Pokaż tą wersję';
$labels['restore'] = 'Przywróć tą wersję';
$labels['objectchangelognotavailable'] = 'Historia nie jest dostępna dla tego obiektu.';
$labels['tabsharing'] = 'Udostępnianie';
$labels['aclnorights'] = 'Nie masz uprawnień administratora do tego folderu.';
