<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['objectchangelog'] = 'História';
$labels['objectdiff'] = 'Alterações da $rev1 para $rev2';
$labels['user'] = 'Usuário';
$labels['actiondelete'] = 'Deletado';
$labels['tabsharing'] = 'Compartilhamento';
