<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['compare'] = 'Comparar';
$labels['objectchangelog'] = 'Histórico';
$labels['objectdiff'] = 'Diferenças entre $rev1 e $rev2';
$labels['revision'] = 'Revisão';
$labels['user'] = 'Utilizador';
$labels['operation'] = 'Ação';
$labels['actionappend'] = 'Guardado';
$labels['actionmove'] = 'Movido';
$labels['actiondelete'] = 'Eliminado';
$labels['showrevision'] = 'Mostrar esta versão';
$labels['restore'] = 'Restaurar esta versão';
$labels['tabsharing'] = 'Partilha';
