<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Показать Историю';
$labels['compare'] = 'Сравнить';
$labels['objectchangelog'] = 'История';
$labels['objectdiff'] = 'Изменения с $rev1 до $rev2';
$labels['revision'] = 'Ревизия';
$labels['user'] = 'Пользователь';
$labels['operation'] = 'Действие';
$labels['actionreceive'] = 'Получено';
$labels['actionappend'] = 'Сохранено';
$labels['actionmove'] = 'Перемещено';
$labels['actiondelete'] = 'Удалённые';
$labels['actionread'] = 'Отмечено как прочитаное';
$labels['actionflagset'] = 'Флаг установлен';
$labels['actionflagclear'] = 'Флаг удалён';
$labels['showrevision'] = 'Показать эту версию';
$labels['restore'] = 'Восстановить эту версию';
$labels['objectchangelognotavailable'] = 'История недоступна для этого объекта.';
$labels['tabsharing'] = 'Поделиться';
$labels['aclnorights'] = 'У вас нет прав администратора для этой папки.';
