<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['compare'] = 'Primerjaj';
$labels['objectchangelog'] = 'Zgodovina';
$labels['revision'] = 'Verzija';
$labels['user'] = 'Uporabnik';
$labels['operation'] = 'Dejanje';
$labels['actionappend'] = 'Shranjeno';
$labels['actionmove'] = 'Premaknjeno';
$labels['actiondelete'] = 'Izbrisano';
$labels['showrevision'] = 'Prikaži to verzijo';
$labels['restore'] = 'Obnovi to verzijo';
$labels['tabsharing'] = 'Deli z ostalimi';
