<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = 'Visa historik';
$labels['compare'] = 'Jämför';
$labels['objectchangelog'] = 'Historik';
$labels['objectdiff'] = 'Ändringar från $rev1 till $rev2';
$labels['revision'] = 'Revision';
$labels['user'] = 'Användare';
$labels['operation'] = 'Åtgärd';
$labels['actionreceive'] = 'Mottagen';
$labels['actionappend'] = 'Sparad';
$labels['actionmove'] = 'Flyttad';
$labels['actiondelete'] = 'Borttagen';
$labels['actionread'] = 'Markera som läst';
$labels['actionflagset'] = 'Flagga satt';
$labels['actionflagclear'] = 'Flagga borttagen';
$labels['showrevision'] = 'Visa denna version';
$labels['restore'] = 'Återställ denna verson';
$labels['tabsharing'] = 'Delning';
