<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['compare'] = 'เปรียบเทียบ';
$labels['objectchangelog'] = 'ประวัติ';
$labels['revision'] = 'รุ่นการปรับปรุง';
$labels['user'] = 'ผู้ใช้';
$labels['operation'] = 'การกระทำ';
$labels['actionappend'] = 'บันทึกเรียบร้อย';
$labels['actionmove'] = 'ย้ายเรียบร้อย';
$labels['actiondelete'] = 'ลบเรียบร้อย';
$labels['showrevision'] = 'แสดงรุ่นการปรับปรุงนี้';
$labels['restore'] = 'ย้อนกลับไปยังรุ่นการปรับปรุงนี้';
$labels['tabsharing'] = 'แบ่งปัน';
