<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['compare'] = 'Порівняти';
$labels['objectchangelog'] = 'Історія';
$labels['revision'] = 'Ревізія';
$labels['user'] = 'Користувач';
$labels['operation'] = 'Дія';
$labels['actionappend'] = 'Збережено';
$labels['actionmove'] = 'Переміщено';
$labels['actiondelete'] = 'Вилучено';
$labels['showrevision'] = 'Показати дану весію';
$labels['restore'] = 'Відновити дану версію';
$labels['tabsharing'] = 'Спільне використання';
