<?php
/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */
$labels['showhistory'] = '显示历史';
$labels['compare'] = '对比';
$labels['objectchangelog'] = '历史';
$labels['user'] = '用户';
$labels['operation'] = '应用';
$labels['actionread'] = '标记为已读';
$labels['tabsharing'] = '分享';
