<?php

$labels['suspects_urls_menu'] = 'Gestion des URLs suspectes';
$labels['suspects_urls_title'] = 'Utilisez ce menu pour gérer les urls suspectes.';
$labels['suspects_urls'] = 'URLS Suspectes';
$labels['title_add_suspects_urls'] = 'Ajouter une Url ou un nom de domaine';
$labels['add_suspects_urls'] = 'Ajouter';
$labels['access_denied'] = "Accès refusé. Vous n'avez pas les droits nécessaires.";
$labels['url_already_exist'] = 'Cette adresse e-mail existe déjà';
$labels['url_added_successfully'] = 'L\'URL a été ajoutée avec succès';
$labels['url_add_error'] = 'L\'URL n\'a pas pu être ajoutée';
$labels['status_updated_successfully'] = 'Le statut a été modifié avec succès';
$labels['status_updated_error'] = 'Le statut n\'a pas été modifié';
$labels['confirm_url_deletion'] = 'Êtes-vous sûr de vouloir supprimer cette URL ?';
$labels['url_deleted_successfully'] = 'L\'URL a été supprimée avec succès';
$labels['url_delete_error'] = 'L\'URL n\'a pas été supprimée';
$labels['suspect'] = 'Suspecte';
$labels['blocked'] = 'Bloquée';
$labels['delete'] = 'Supprimer';