<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/moncompte/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/

$labels = array();

$labels['annuaire'] = 'Contacts';
$labels['annuaires'] = 'Annuaire';
$labels['all'] = 'Tous';
$labels['persons'] = 'Personnes';
$labels['groups'] = 'Groupes';
$labels['functions'] = 'Fonctionnelles';
$labels['services'] = 'Services';
$labels['units'] = 'Unités';
$labels['resources'] = 'Ressources';
$labels['applications'] = 'Applicatives';
$labels['gototree'] = 'Afficher l\'objet dans l\'arborescence';
$labels['gototreename'] = 'Atteindre';


