<?php
$labels = array();
$labels['task'] = 'Projet';
$labels['title'] = 'Projet';

// Liste des applications
$labels['webconf'] = 'Webconf';
$labels['webconf_title'] = 'Afficher ou masquer la Webconf';
$labels['pad'] = 'Pad';
$labels['pad_title'] = 'Afficher ou masquer le Pad';
$labels['stockage'] = 'Stockage';
$labels['stockage_title'] = 'Afficher ou masquer le Stockage';
$labels['ariane'] = 'Discussion';
$labels['ariane_title'] = 'Afficher ou masquer la Discussion';