<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/

$labels['sharing'] = 'Partage';
$labels['myrights'] = 'Droits d\'accès';
$labels['myobjects'] = 'Autres droits';
$labels['username'] = 'Utilisateur :';
$labels['advanced'] = 'Mode avancé';
$labels['newuser'] = 'Ajouter l\'entrée';
$labels['editperms'] = 'Modifier les permissions';
$labels['actions'] = 'Actions des droits d\'accès...';
$labels['anyone'] = 'Tous les utilisateurs (n\'importe qui)';
$labels['anonymous'] = 'Invités (anonyme)';
$labels['identifier'] = 'Identifiant';

$labels['acll'] = 'Consultation';
$labels['aclr'] = 'Lire les messages';
$labels['acls'] = 'Garder l\'état vu';
$labels['aclw'] = 'Écrire une étiquette';
$labels['acli'] = 'Insérer (Copier dans)';
$labels['aclp'] = 'Envoyer';
$labels['aclc'] = 'Créer des sous-dossiers';
$labels['aclk'] = 'Créer des sous-dossiers';
$labels['acld'] = 'Supprimer des messages';
$labels['aclt'] = 'Supprimer des messages';
$labels['acle'] = 'Purger';
$labels['aclx'] = 'Supprimer un dossier';
$labels['acla'] = 'Administrer';

$labels['aclfull'] = 'Gestion';
$labels['aclother'] = 'Autre';
$labels['aclread'] = 'Lecture';
$labels['aclwrite'] = 'Écriture';
$labels['acldelete'] = 'Suppression';
$labels['aclfreebusy'] = 'Afficher';
$labels['aclprivate'] = 'Privé';
$labels['aclsend'] = 'Émission';

$labels['shortacll'] = 'Consultation';
$labels['shortaclr'] = 'Lecture';
$labels['shortacls'] = 'Conserver';
$labels['shortaclw'] = 'Écriture';
$labels['shortacli'] = 'Insérer';
$labels['shortaclp'] = 'Envoyer';
$labels['shortaclc'] = 'Créer';
$labels['shortaclk'] = 'Créer';
$labels['shortacld'] = 'Suppression';
$labels['shortaclt'] = 'Suppression';
$labels['shortacle'] = 'Purger';
$labels['shortaclx'] = 'Supprimer un dossier';
$labels['shortacla'] = 'Administrer';

$labels['shortaclfull'] = 'Gestion';
$labels['shortaclother'] = 'Autre';
$labels['shortaclread'] = 'Lecture';
$labels['shortaclwrite'] = 'Écriture';
$labels['shortacldelete'] = 'Suppression';
$labels['shortaclprivate'] = 'Privé';
$labels['shortaclfreebusy'] = 'Afficher';
$labels['shortaclsend'] = 'Émission';

$labels['longacll'] = 'Ce dossier est visible dans les listes et peut être souscrit';
$labels['longaclr'] = 'Le dossier peut-être ouvert pour lecture';
$labels['longacls'] = 'L\'étiquette Lu peut-être changée';
$labels['longaclw'] = 'Les étiquettes et les mot-clés peuvent-être changé, sauf pour Vu et Supprimé';
$labels['longacli'] = 'Les messages peuvent-être écrit ou copié dans le dossier';
$labels['longaclp'] = 'Les messages peuvent-être envoyé dans ce dossier';
$labels['longaclc'] = 'Les dossiers peuvent-être créer (ou renommer) directement depuis ce dossier';
$labels['longaclk'] = 'Les dossiers peuvent-être créer (ou renommer) directement depuis ce dossier';
$labels['longacld'] = 'L\'étiquette de suppression des messages peut-être modifiée';
$labels['longaclt'] = 'L\'étiquette de suppression des messages peut-être modifiée';
$labels['longacle'] = 'Les messages peuvent-être purgés';
$labels['longaclx'] = 'Le dossier peut-être supprimé ou renommé';
$labels['longacla'] = 'Les droits d\'accès au dossier peuvent-être modifiés';

$labels['longaclfull'] = 'Contrôle total, dossier d\'administration inclus';
$labels['longaclread'] = 'Donner le droit de lecture à l\'utilisateur ou au groupe';
$labels['longaclwrite'] = 'Donner le droit d\'écriture à l\'utilisateur ou au groupe';
$labels['longacldelete'] = 'Donner le droit de suppression à l\'utilisateur ou au groupe';
$labels['longaclprivate'] = 'Donner la possibilité à l\'utilisateur ou au groupe de voir les évènements privés';
$labels['longaclfreebusy'] = 'Afficher les disponibilités sans avoir le détail';
$labels['longaclsend'] = 'Donner le droit d\'émission à l\'utilisateur ou au groupe';

$messages['deleting'] = 'Suppression des droits d\'accès…';
$messages['saving'] = 'Sauvegarde des droits d\'accès…';
$messages['updatesuccess'] = 'Les droits d\'accès ont été changés avec succès';
$messages['deletesuccess'] = 'Les droits d\'accès ont été supprimés avec succès';
$messages['createsuccess'] = 'Les droits d\'accès ont été ajoutés avec succès';
$messages['updateerror'] = 'Impossible de mettre à jour les droits d\'accès';
$messages['deleteerror'] = 'Impossible de supprimer les droits d\'accès';
$messages['createerror'] = 'Impossible d\'ajouter des droits d\'accès';
$messages['deleteconfirm'] = 'Êtes-vous sûr de vouloir retirer les droits d\'accès du/des utilisateur(s) sélectionné(s) ?';
$messages['norights'] = 'Aucun droit n\'a été spécifié !';
$messages['nouser'] = 'Aucun nom d\'utilisateur n\'a été spécifié !';

$labels['objectcalendar'] = 'Calendrier';
$labels['objectcontact'] = 'Carnet d\'adresses';
$labels['objecttask'] = 'Liste de tâches';

$labels['longobjectcalendar'] = 'Partager également le calendrier de la boite aux lettres';
$labels['longobjectcontact'] = 'Partager également le carnet d\'adresses de la boite aux lettres';
$labels['longobjecttask'] = 'Partager également la liste de tâches de la boite aux lettres';

?>
