<?php
/**
 * Roundpad pads storage engine
 *
 * Translations
 *
 * Copyright (C) 2016 PNE Annuaire et Messagerie MEDDE/MLETR
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
$labels['files'] = 'Documents';
$labels['create'] = 'Create';
$labels['save'] = 'Save';
$labels['cancel'] = 'Cancel';
$labels['open'] = 'Open';
$labels['foldercreate'] = 'New folder';
$labels['folderedit'] = 'Edit folder';
$labels['folderdelete'] = 'Delete folder';
$labels['folderinside'] = 'Add in folder';
$labels['foldername'] = 'Folder name';
$labels['filecreate'] = 'New document';
$labels['filetype'] = 'Document type';
$labels['folder'] = 'New folder';
$labels['document'] = 'New document';
$labels['createfile'] = 'Create a document';
$labels['name'] = 'Name';
$labels['created'] = 'Created';
$labels['url'] = 'URL';
$labels['owner'] = 'Owner';
$labels['path'] = 'Path';
$labels['mtime'] = 'Modified';
$labels['type'] = 'Type';
$labels['view'] = 'Open';
$labels['viewfile'] = 'Open this document';
$labels['rename'] = 'Rename this document';
$labels['deletefile'] = 'Delete document(s)';
$labels['edit'] = 'Edit';
$labels['editfile'] = 'Edit this document';
$labels['fileedit'] = 'Document properties';
$labels['collection_etherpad'] = 'All my Etherpad';
$labels['collection_ethercalc'] = 'All my Ethercalc';
$labels['foldercreating'] = 'Creating folder...';
$labels['folderupdating'] = 'Updating folder...';
$labels['folderdeleting'] = 'Deleting folder...';
$labels['folderdeleteconfirm'] = 'Are you sure you want to delete selected folder?';
$labels['folderdeletenotice'] = 'Folder deleted successfully.';
$labels['folderupdatenotice'] = 'Folder updated successfully.';
$labels['foldercreatenotice'] = 'Folder created successfully.';
$labels['fileupdating'] = 'Updating document...';
$labels['filemoving'] = 'Moving document(s)...';
$labels['filecopying'] = 'Copying document(s)...';
$labels['filedeleting'] = 'Deleting document(s)...';
$labels['filedeleteconfirm'] = 'Are you sure you want to delete selected document(s)?';
$labels['filedeletenotice'] = 'Document(s) deleted successfully.';
$labels['filemovenotice'] = 'Document(s) moved successfully.';
$labels['filecopynotice'] = 'Document(s) copier successfully.';
$labels['filecreatenotice'] = 'Document created successfully.';
$labels['allfolders'] = 'search in all folders';
$labels['getexistingpad'] = 'Save an existing document';
$labels['padname'] = 'Document name';
$labels['fileurl'] = 'Document URL';
$labels['fileowner'] = 'Document owner';
$labels['me'] = 'Me';
$labels['other'] = 'Other';
$labels['etherpad'] = 'Etherpad';
$labels['ethercalc'] = 'Ethercalc';
$labels['message_subject'] = 'Sending %%file_type%% document "%%file_name%%"';
$labels['message_body'] = 'Here is link to the %%file_type%% document "%%file_name%%" : %%file_url%%';
$labels['cantlistfolders'] = 'Can\'t list folders';
$labels['cantlistfiles'] = 'Can\'t list documents';
$labels['cantcreatefile'] = 'Can\'t create document';
$labels['cantdeletefiles'] = 'Can\'t delete document(s)';
$labels['cantmovefiles'] = 'Can\'t move document(s)';
$labels['canteditfile'] = 'Can\'t edit document';
$labels['cantcreatefolder'] = 'Can\'t create folder';
$labels['cantdeletefolder'] = 'Can\'t delete folder';
$labels['cantmovefolder'] = 'Can\'t move folder';
$labels['fileskip'] = 'Skip';
$labels['fileskipall'] = 'Skip all';
$labels['fileoverwrite'] = 'Overwrite';
$labels['fileoverwriteall'] = 'Overwrite all';
$labels['filemoveconfirm'] = 'This action is going to overwrite the destination file: <b>$file</b>.';
$labels['arialabelsearchform'] = 'Documents search form';
$labels['arialabelquicksearchbox'] = 'Search input';
$labels['arialabellistoptions'] = 'Documents list options';
$labels['arialabelfolderoptions'] = 'Folder actions';
$labels['arialabelfileeditform'] = 'Document editing form';
$labels['arialabelfoldercreateform'] = 'Folder creation form';
$labels['arialabelfoldereditform'] = 'Folder editing form';
$labels['arialabelfolderlist'] = 'Folder/Collection selection';
$labels['arialabelfileselectdialog'] = 'Document selection dialog';
$labels['arialabelattachmentoptions'] = 'Attachment save options';
$labels['arialabelfilesavedialog'] = 'Document(s) saving dialog';
$labels['arialabelfileprops'] = 'Document properties';
$labels['arialabelfilecontent'] = 'Document content';

?>
