<?php
$labels = array();
$labels['task'] = 'Discussion';
$labels['title'] = 'Discussion avec Ariane';


$labels['rocket_error_title'] = "Erreur de chargement d'Ariane";
$labels['rocket_admin_auth_error'] = "Erreur de connexion à Ariane : la connexion aux API en tant qu'administrateur a échoué. Veuillez réessayer, si le problème persiste contactez votre cellule informatique.";
$labels['rocket_create_user_error'] = "Erreur de connexion à Ariane : la création de l'utilisateur a échoué. Erreur du serveur : ";
$labels['rocket_create_token_error'] = "Erreur de connexion à Ariane : la création du token a échoué.";


$labels['courrielleur_title_page'] = 'Ariane doit maintenant être utilisée dans le navigateur.';
$labels['courrielleur_text_page_1'] = 'Pour une utilisation optimale d\'Ariane, il est nécessaire d\'ouvrir Ariane depuis Mél web.';
$labels['courrielleur_text_page_2'] = 'Les capacités d\'affichage de votre version du courrielleur sont incompatibles avec Ariane.';
$labels['courrielleur_text_page_3'] = 'Pour ouvrir Ariane, copier/coller le lien suivant dans votre navigateur : https://mel.din.developpement-durable.gouv.fr/?_task=ariane';