<?php
$labels = array();
$labels['portal'] = "Accueil";
$labels['news'] = "S'informer";
//Modules

//Flux_rss
$labels['rss_sample_header'] = "Ministère de la transition écologique";
$labels['rss_sample_body'] = "Longue vie aux objets : lancement de la campagne Nos objets ont plein d'avenirs";
$labels['rss_sample_footer'] = "Economiecirculaire";
$labels['add_flux'] = "Ajouter un flux";
$labels['choose_intra'] = "Choisir le site intranet à afficher";
$labels['choose_web_site'] = "Sélectionner un site";
$labels['choose_format'] = "Choisir le format";
$labels['little_format'] = "Petit format";
$labels['big_format'] = "Grand format";
$labels['choose_mode_showed'] = "Choisir le mode d'affichage";
$labels['light_background'] = "Fond clair";
$labels['dark_background'] = "Fond sombre";


//Left_Menu
$labels['index'] = "Tableau de bord ";
$labels['news'] = "Informations";
$labels['config'] = "Configuration";

//My Day
$labels['agenda'] = "Agenda ";
$labels['tasks'] = "Tâches";
$labels['my_day'] = "Ma journée";
$labels['headline'] = "Informations";
$labels['thematic_1'] = "Thématique 1";
$labels['thematic_2'] = "Thématique 2";
$labels['workspaces'] = "Mes espaces de travail";

//Workspaces
$labels['tak'] = "Épingler";
$labels['untak'] = "Désépingler";

$labels["no_event_today"] = "Pas de réunion prévue aujourd'hui.";
$labels["next_agenda_event"] = "Prochaine réunion planifiée le : {date} à {horaire}";
$labels["next_agenda_event_all_day"] = "Prochaine réunion planifiée le : {date} toute la journée";
$labels["other_next_agenda_event"] = "Le {date} à {horaire}";
$labels["other_next_agenda_event_all_day"] = "Le {date} toute la journée";

//Workspaces button title
$labels['button_title_calendar'] = "Ouvrir le calendrier de l'espace de travail";
$labels['button_title_doc'] = "Ouvrir les documents de l'espace de travail";
$labels['button_title_channel'] = "Ouvrir le canal de discussion de l'espace de travail";
$labels['button_title_mail'] = "Ouvrir la messagerie mail de l'espace de travail";