<?php
$labels = array();
$labels['task'] = 'Générer une signature';
$labels['signaturestitle'] = 'Utilisez ce menu pour générer automatiquement une signature au format ministériel';
$labels['title'] = 'Générateur de signature';

$labels['informationslabel'] = "Mes informations :";
$labels['neededfields'] = "(*) champs obligatoires";
$labels['name'] = "Nom";
$labels['jobtitle'] = "Fonction / Intitulé de poste";
$labels['service'] = "Service";
$labels['address'] = "Adresse";
$labels['postcode'] = "Code postal ville";
$labels['phone'] = "Téléphone fixe";
$labels['mobile'] = "Téléphone mobile";
$labels['office'] = "Bureau (ou pôle)";
$labels['signaturelabel'] = "Ma signature :";
$labels['roomnumber'] = "Bureau : ";
$labels['department'] = "Direction / Département";
$labels['mobilephone'] = "Mobile : ";
$labels['phonephone'] = "Tel : ";
$labels['clictocopy'] = "Copier la signature";
$labels['signaturecopied'] = "Copiée !";
$labels['logo'] = "Choix du logo";
$labels['links'] = "Choix des liens";
$labels['linksselection'] = "Liens";