<?php
/* Author: Tobias Fischer */

$labels = array();
$labels['removeall'] = 'Alle Anhänge löschen';
$labels['removeattachment'] = 'Diesen Anhang löschen';

$messages = array();
$messages['removeoneconfirm'] = 'Bist du sicher, dass du diesen Anhang löschen möchtest?';
$messages['removeallconfirm'] = 'Bist du sicher, dass du alle Anhänge löschen möchtest?';
$messages['removing'] = 'Anhänge werden gelöscht...';
$messages['attachmentremoved'] = 'Anhänge gelöscht';
$messages['removefailed'] = 'Fehler: Anhänge konnten nicht gelöscht werden';

?>