<?php
/* Author: Philip Weir */

$labels = array();
$labels['removeall'] = 'Remove all attachments';
$labels['removeattachment'] = 'Remove this attachment';

$messages = array();
$messages['removeoneconfirm'] = 'Are you sure you want to remove this attachment?';
$messages['removeallconfirm'] = 'Are you sure you want to remove all attachments?';
$messages['removing'] = 'Removing attachment(s)...';
$messages['attachmentremoved'] = 'Attachment(s) removed';
$messages['removefailed'] = 'Error: Could not remove attachment(s)';

?>