<?php
/* Author: Thomas Payen */

$labels = array();
$labels['removeall'] = 'Supprimer toutes les pièces jointes';
$labels['removeattachment'] = 'Supprimer la pièce jointe';

$messages = array();
$messages['removeoneconfirm'] = 'Êtes-vous sûr de vouloir supprimer cette pièce jointe du message ?';
$messages['removeallconfirm'] = 'Êtes-vous sûr de vouloir supprimer toutes les pièces jointes du message ?';
$messages['removing'] = 'Suppression du/des pièce(s) jointe(s) du message...';
$messages['attachmentremoved'] = 'La/les pièces(s) jointe(s) a/ont été supprimée(s) du message';
$messages['removefailed'] = 'Erreur: impossible de supprimer la/les pièce(s) jointe(s) du message';

?>