<?php
/* Author: Philip Weir */

$labels = array();
$labels['removeall'] = 'Remover todos os anexos';
$labels['removeattachment'] = 'Remover este anexo';

$messages = array();
$messages['removeoneconfirm'] = 'Tem a certeza que pretende remover este anexo?';
$messages['removeallconfirm'] = 'Tem a certeza que pretende remover todos os anexos?';
$messages['removing'] = 'A remover o(s) anexo(s)...';
$messages['attachmentremoved'] = 'Anexo(s) removido(s)';
$messages['removefailed'] = 'Erro: Não foi possível remover o(s) anexo(s)';

?>