<?php

$labels = array();
$labels['planify'] = 'Planifier';
$labels['flex-office'] = 'Flex office';
$labels['event-location-flex-office'] = $labels['flex-office'];
$labels['event-location-resource'] = 'Réserver une ressource';
$labels['locality'] = 'Ville';
$labels['batiment'] = 'Batiment';
$labels['etage'] = 'Etage';
$labels['roomnumber'] = 'Salle';
$labels['caracteristiques'] = 'Filtres';
$labels['today'] = 'Aujourd\'hui';
$labels['resarcs'] = 'Réserver une ressource';
$labels['no-resources'] = 'Aucune ressources';
$labels['busy'] = 'Occupé';
$labels['automatic-resa-title'] = 'Réservation : %0';
$labels['me'] = 'Moi';
$labels['prev_day'] = 'Jour précédent';
$labels['next_day'] = 'Jour suivant';
$labels['change_date'] = 'Changement de date';
$labels['resource_located_at'] = 'Ressource située à :';
$labels['city'] = 'Ville :';
