<?php

$labels = array();
$labels['planify'] = 'Planifier';
$labels['flex-office'] = 'Flex office';
$labels['event-location-flex-office'] = $labels['flex-office'];
$labels['locality'] = 'Ville';
$labels['batiment'] = 'Batiment';
$labels['etage'] = 'Etage';
$labels['roomnumber'] = 'Salle';
$labels['caracteristiques'] = 'Filtres';
$labels['today'] = 'Aujourd\'hui';
$labels['resarcs'] = 'Réserver une ressource';
$labels['no-resources'] = 'Aucune ressources';
$labels['busy'] = 'Occupé';
$labels['automatic-resa-title'] = 'Réservation : %0';