<?php
$labels = array();
$labels['useful_links'] = 'Liens utiles';
$labels['My_useful_links'] = 'Liens utiles';
$labels['find_useful_link'] = 'Rechercher un lien utile';
$labels['pined_links'] = 'Mes liens utiles épinglés';
$labels['all_useful_links'] = 'Tous mes liens utiles';

$labels['create_new_link'] = 'Création d\'un nouveau lien';
$labels['update_new_link'] = 'Modification d\'un nouveau lien';
$labels['modify_link_element'] = 'Modifier l\'élément';
$labels['delete_link_element'] = 'Supprimer l\'élément';
$labels['confirm_delete_link_element'] = 'Voulez-vous supprimer ce lien ?';

$labels['update_new_folder'] = 'Modification d\'un dossier';
$labels['folder_name'] = 'Nom du dossier';

$labels['required_fields'] = 'Champs obligatoires';
$labels['link_name'] = 'Nom du lien';
$labels['link_title'] = 'Titre du lien';
$labels['link_url'] = 'Adresse de la page';

$labels['add'] = 'Ajouter';
$labels['update'] = 'Modifier';

