<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'μέχρι';
$labels['alarmemail'] = 'Αποστολή αλληλογραφίας';
$labels['alarmdisplay'] = 'Εμφάνιση μηνύματος';
$labels['alarmaudio'] = 'Αναπαραγωγή ήχου';
$labels['alarmdisplayoption'] = 'Μήνυμα';
$labels['alarmemailoption'] = 'Ηλεκτρονική αλληλογραφία';
$labels['alarmaudiooption'] = 'Ήχος';
$labels['trigger-H'] = 'ώρες πριν';
$labels['trigger+M'] = 'λεπτά μετά';
$labels['trigger+H'] = 'ώρες μετά';
$labels['trigger+D'] = 'ημέρες μετά';
$labels['triggerend-M'] = 'λεπτά πριν το τέλος';
$labels['triggerend-H'] = 'ώρες πριν το τέλος';
$labels['triggerend-D'] = 'ημέρες πριν το τέλος';
$labels['triggerend+M'] = 'λεπτά πριν το τέλος';
$labels['triggerend+D'] = 'ημέρες μετά το τέλος';
$labels['frequency'] = 'Επανάληψη';
$labels['recurrencend'] = 'μέχρι';
$labels['forntimes'] = ''; // old
$labels['statusorganizer'] = 'Οργανωτής';
$labels['statuscompleted'] = 'Ολοκληρώθηκε';
$labels['savingdata'] = 'Αποθήκευση δεδομένων...';
