<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'kuni';
$labels['alarmemail'] = 'Saada kiri';
$labels['alarmdisplay'] = 'Näita sõnumit';
$labels['alarmaudio'] = 'Esita heli';
$labels['alarmdisplayoption'] = 'Sõnum';
$labels['alarmemailoption'] = 'E-post';
$labels['alarmaudiooption'] = 'Heli';
$labels['trigger-M'] = 'minutit enne';
$labels['trigger-H'] = 'tundi enne';
$labels['trigger-D'] = 'päeva enne';
$labels['trigger+M'] = 'minutit pärast';
$labels['trigger+H'] = 'tundi pärast';
$labels['trigger+D'] = 'päeva pärast';
$labels['addalarm'] = 'Lisa alarm';
$labels['dismissall'] = 'Eira kõiki';
$labels['dismiss'] = 'Eira';
$labels['snooze'] = 'Lükka edasi';
$labels['showmore'] = 'Näita rohkem...';
$labels['recurring'] = 'Kordused';
$labels['frequency'] = 'Kordamine';
$labels['never'] = 'mitte kunagi';
$labels['bydates'] = 'On';
$labels['bymonths'] = 'On';
$labels['forever'] = 'igavesti';
$labels['recurrencend'] = 'kuni';
$labels['forntimes'] = ''; // old
$labels['statusorganizer'] = 'Organiseerija';
$labels['statusaccepted'] = 'Vastu võetud';
$labels['statusdeclined'] = 'Tagasi lükatud';
$labels['statusunknown'] = 'Teadmata';
$labels['statuscompleted'] = 'Valmis';
$labels['statusin-process'] = 'Töös';
$labels['itipcancellation'] = 'Tühistatud:';
$labels['itipreply'] = 'Vastus aadressile';
$labels['itipaccepted'] = 'Võta vastu';
$labels['itiptentative'] = 'Võib-olla';
$labels['itipdeclined'] = 'Lükka tagasi';
$labels['itipdelegated'] = 'Delegeeri';
$labels['itipneeds-action'] = 'Lükka edasi';
$labels['itipcomment'] = 'nu vastus';
$labels['itipeditresponse'] = 'Sisesta vastuse tekst';
$labels['itipsendercomment'] = 'Saatja kommentaar:';
$labels['itipsuppressreply'] = 'Ära saada vastust';
$labels['openpreview'] = 'Ava eelvaade';
$labels['savingdata'] = 'Andmete salvestamine...';
$labels['savein'] = 'Save in';
