<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'até';
$labels['alarmemailoption'] = 'Email';
$labels['frequency'] = 'Repetir';
$labels['recurrencend'] = 'até';
$labels['forntimes'] = ''; // old
$labels['statusorganizer'] = 'Organizador';
$labels['statustentative'] = 'Tentativa';
$labels['statusunknown'] = 'Desconhecido';
$labels['savingdata'] = 'Salvando dados...';
