<?php
$labels = array();
$labels['my_workspaces'] = 'Mes espaces de travail';
$labels['back'] = 'Retour';
$labels['home'] = 'Accueil';
$labels['calendar'] = 'Agenda';
$labels['mail'] = 'Messagerie';
$labels['documents'] = 'documents';
$labels['rocketchat'] = 'Discussion';
$labels['tasks'] = 'Tâches';
$labels['params'] = 'Paramètres';
$labels['create_event'] = 'Créer un évènement';
$labels['create_task'] = 'Créer une tâche';
$labels["open_ariane"] = "Afficher la discussion instantanée de l'espace de travail";
$labels["close_ariane"] = "Cacher la discussion instantanée de l'espace de travail";
$labels["last_day"] = "Jour précédent";
$labels["next_day"] = "Jour suivant";

$labels["wekan_todo"] = "À faire";
$labels["wekan_in_progress"] = "En cours";
$labels["wekan_do"] = "Fait";

$labels["useful_links"] = "Liens utiles";
$labels["infos"] = "Informations";

$labels["create_mail"] = "Envoyer un message aux membres";
$labels["create_webconf"] = "Commencer une visioconférence";
$labels["create_webconf_params"] = "Nouvelle visioconférence paramétrable";