<?php
$labels = array();
$labels['my_workspaces'] = 'Mes espaces de travail';
$labels['back'] = 'Retour';
$labels['home'] = 'Accueil';
$labels['calendar'] = 'Agenda';
$labels['rocketchat'] = 'Discussion';
$labels['tasks'] = 'Tâches';
$labels['params'] = 'Paramètres';
$labels['create_event'] = 'Créer un évènement';
$labels['create_task'] = 'Créer une tâche';
$labels["open_ariane"] = "Afficher la discussion instantanée de l'espace de travail";
$labels["close_ariane"] = "Cacher la discussion instantanée de l'espace de travail";