<?php
$labels = array();
$labels['hide this help'] = 'Masquer cette aide';
$labels['hide all help'] = 'Masquer toutes les aides';
$labels['close help'] = 'Fermer l\'aide';
$labels['to display this help again, you can go to'] = 'Pour réafficher cette aide, vous pouvez vous rendre sur ';
$labels['Do not display this help again during my future connections'] = 'Enregistrer ce choix pour mes futures connexions';