<?php
/**
 * Plugin Mel Junk for Roundcube
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$labels = array();
$labels['title'] = 'Message(s) indésirable(s)';
$labels['title_long'] = 'Message(s) indésirable(s) : que voulez-vous faire ?';
$labels['junk'] = 'Valider';
$labels['admin'] = 'Signaler à l\'administrateur';
$labels['buttontitle'] = 'Marquer comme indésirable';
$labels['add to junk folder'] = 'Mettre le(s) message(s) dans le dossier Indésirables';
$labels['send message to administrator'] = 'Signaler le(s) message(s) à l\'administrateur';
$labels['arialabeljunkoptions'] = 'Options de message indésirable';
$labels['buttonnotjunk'] = 'Ce message n\'est pas un message indésirable';

