<?php
/**
 * Localizations for the Roundrive plugin
 *
 * @version @package_version@
 * @author Thomas Payen <thomas.payen@apitech.fr>
 *
 * This plugin is inspired by kolab_files plugin
 * Use flysystem library : https://github.com/thephpleague/flysystem
 * With flysystem WebDAV adapter : https://github.com/thephpleague/flysystem-webdav
 *
 * Copyright (C) 2015 PNE Annuaire et Messagerie MEDDE/MLETR
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
$labels['files'] = 'Fichiers';
$labels['filepreview'] = 'Fichier d\'aperçu';
$labels['saveall'] = 'Enregistrer tout dans le drive...';
$labels['saveto'] = 'Enregistrer dans le drive...';
$labels['saveas'] = 'Enregistrer sous:';
$labels['create'] = 'Créer';
$labels['save'] = 'Enregistrer';
$labels['cancel'] = 'Annuler';
$labels['fromcloud'] = 'Depuis le drive...';
$labels['selectfiles'] = 'Sélectionnez le(s) fichier(s) à attacher..';
$labels['attachsel'] = 'Attachement sélectionné';
$labels['foldercreate'] = 'Nouveau répertoire';
$labels['folderdelete'] = 'Supprimer le répertoire';
$labels['folderinside'] = 'Ajouter à l\'intérieur';
$labels['foldername'] = 'Nom du répertoire';
$labels['name'] = 'Nom';
$labels['mtime'] = 'Modifié';
$labels['type'] = 'Type';
$labels['upload'] = 'Téléverser';
$labels['uploadfile'] = 'Téléversement de fichier(s)';
$labels['get'] = 'Télécharger';
$labels['getfile'] = 'Téléchargement de fichier(s)';
$labels['view'] = 'Voir';
$labels['viewfile'] = 'Voir le fichier';
$labels['rename'] = 'Renommer le fichier';
$labels['deletefile'] = 'Supprimer le(s) fichier(s)';
$labels['edit'] = 'Modifier';
$labels['editfile'] = 'Modifier le fichier';
$labels['save'] = 'Enregistrer';
$labels['savefile'] = 'Sauvegarder le fichier';
$labels['printfile'] = 'Imprimer le fichier';
$labels['fileedit'] = 'Propriétés du fichier';
$labels['collection_audio'] = 'Son';
$labels['collection_video'] = 'Vidéo';
$labels['collection_image'] = 'Images';
$labels['collection_document'] = 'Documents';
$labels['uploading'] = 'Téléversement de(s) fichier(s)...';
$labels['attaching'] = 'Attachement de fichier(s)...';
$labels['foldercreating'] = 'Création d\'un répertoire...';
$labels['folderupdating'] = 'Mise à jour d\'un répertoire...';
$labels['folderdeleting'] = 'Suppression d\'un répertoire...';
$labels['folderdeleteconfirm'] = 'Êtes-vous sûr de de vouloir supprimer le répertoire sélectionné ?';
$labels['folderdeletenotice'] = 'Le répertoire a été supprimé.';
$labels['folderupdatenotice'] = 'Le répertoire a été mis à jour.';
$labels['foldercreatenotice'] = 'Le répertoire a été créé.';
$labels['saveallnotice'] = '$n fichier(s) ont été sauvegardé(s)';
$labels['saveallerror'] = 'La sauvegarde de $n fichier(s) a échoué.';
$labels['attacherror'] = 'L\'attachement de fichier(s) depuis le drive a échoué';
$labels['fileupdating'] = 'Modification du fichier...';
$labels['filemoving'] = 'Déplacement de fichier(s)...';
$labels['filecopying'] = 'Copie de fichier(s)...';
$labels['filedeleting'] = 'Suppression de fichier(s)...';
$labels['filedeleteconfirm'] = 'Êtes-vous sûr de de vouloir supprimer les fichiers sélectionnés ?';
$labels['filedeletenotice'] = 'Le(s) fichier(s) ont été supprimé(s).';
$labels['filemovenotice'] = 'Le(s) fichier(s) ont été déplacé(s).';
$labels['filecopynotice'] = 'Le(s) fichier(s) ont été copié(s).';
$labels['uploadsizeerror'] = 'La taille du fichier maximale ($size) est dépassée!';
$labels['allfolders'] = 'Recherche dans tous les répertoires';
$labels['fileskip'] = 'Ignorer';
$labels['fileskipall'] = 'Ignorer tout';
$labels['fileoverwrite'] = 'Écraser';
$labels['fileoverwriteall'] = 'Écraser tout';
$labels['filemoveconfirm'] = 'Cette action va écraser le fichier de destination : <b>$file</b>.';
$labels['arialabelsearchform'] = 'Zone de recherche des fichiers';
$labels['arialabelquicksearchbox'] = 'Champ de recherche';
$labels['arialabellistoptions'] = 'Liste d\'options des fichiers';
$labels['arialabelfolderoptions'] = 'Actions de dossier';
$labels['arialabelfileeditform'] = 'Zone d\'édition de fichier';
$labels['arialabelfoldercreateform'] = 'Zone de création de dossier';
$labels['arialabelfoldereditform'] = 'Zone d\'édition de dossier';
$labels['arialabelfolderlist'] = 'Sélection de dossier';
$labels['arialabelfileselectdialog'] = ' Fenêtre de dialogue de sélection de fichier.';
$labels['arialabelattachmentoptions'] = 'Options d\'enregistrement des pièces jointes';
$labels['arialabelfilesavedialog'] = 'Boite de dialogue d\'enregistrement de fichier(s)';
$labels['arialabelfileprops'] = 'Propriétés du fichier';
$labels['arialabelfilecontent'] = 'Contenu de fichier';
?>
