<?php
$labels = [];
$labels["change_title_confirmation"] = "Attention, le changement de titre de l'espace de travail ne modifiera pas le titre des modules associés (canal de discussion, Drive T, liste de diffusion ...).\r\nConfirmez-vous la demande de changement du titre de votre espace ?";
$labels['tasks'] = 'Tâches';
$labels['forum'] = 'Articles';
$labels['workspace_params'] = 'Paramètres';
$labels['workspace_user'] = 'Paramètres'; 
$labels['tchap'] = 'Tchap';
$labels['home'] = 'Accueil'; 
$labels['wekan'] = 'Kanban';
$labels['stockage'] = 'Documents';
$labels['validation_join_public'] = 'Cet espace est public, cliquez sur "Ok" pour le rejoindre.';
$labels['no_public_error'] = 'Cet espace n\'est pas publique, veuillez contactez un utilisateur pour vous ajouter. Redirection vers la liste des espaces....';