<?php
$labels = [];
$labels["change_title_confirmation"] = "Attention, le changement de titre de l'espace de travail ne modifiera pas le titre des modules associés (canal de discussion, Drive T, liste de diffusion ...).\r\nConfirmez-vous la demande de changement du titre de votre espace ?";
$labels['tasks'] = 'Tâches';
$labels['forum'] = 'Forum';
$labels['workspace_params'] = 'Paramètres';
$labels['workspace_user'] = 'Membres'; 
$labels['home'] = 'Accueil'; 
$labels['wekan'] = 'Kanban';
$labels['stockage'] = 'Documents';