<?php
$labels = array();
$labels['showsuggestionbox'] = 'Proposer une suggestion d\'amélioration du Bureau Numérique';
$labels['suggestionbox'] = 'Faire une suggestion';
$labels['suggestionboxtext'] = "<p>Une nouvelle fonctionnalité, une amélioration d'ergonomie... Vous avez une idée pour l'amélioration du Bureau Numérique ? Vous pouvez nous en faire part ci-dessous.</p><p>En cas de besoin de d'assistance, merci d'utiliser le bouton \"Assistance\" ci-dessus ou de contacter votre Cellule informatique locale.</p><p>Si vous souhaitez en découvrir plus sur le Bureau Numérique, vous pouvez rejoindre le salon de discussion instantanée <a href=\"https://ariane.din.developpement-durable.gouv.fr/channel/Bnum-infos\" target=\"_blank\" title=\"Salon de discussion Bnum-infos\">#Bnum-infos</a>.</p>";
$labels['suggestionboxmessagesend'] = 'Envoi en cours de votre suggestion...';
$labels['suggestionboxmessagesent'] = 'Votre suggestion a correctement été envoyée. Merci';
$labels['suggestionboxmessagesenterror'] = 'Une erreur s\'est produite lors de l\'envoi de votre suggestion. Veuillez réessayer.';
$labels['suggestionboxmessageempty'] = 'Votre message est vide.';