<?php
$labels = array();
$labels['showsuggestionbox'] = 'Proposer une suggestion d\'amélioration du Bureau Numérique';
$labels['suggestionbox'] = 'Faire une suggestion';
$labels['suggestionboxtext'] = 'Une nouvelle fonctionnalité, une amélioration d\'ergonomie... Vous avez une idée pour l\'amélioration du Bureau Numérique ? Vous pouvez nous en faire part ci-dessous.';
$labels['suggestionboxmessagesend'] = 'Envoi en cours de votre suggestion...';
$labels['suggestionboxmessagesent'] = 'Votre suggestion a correctement été envoyée. Merci';
$labels['suggestionboxmessagesenterror'] = 'Une erreur s\'est produite lors de l\'envoi de votre suggestion. Veuillez réessayer.';
$labels['suggestionboxmessageempty'] = 'Votre message est vide.';