<?php
$labels = array();
$labels['my_news'] = "M'informer";
$labels['news'] = "Informations";
$labels['my_strings_of_news'] = "Mes fils d'informations";
$labels['modified'] = "Modifié le";
$labels['created'] = "Publié le";
$labels['no_news'] = "Pas d'information pour le moment.";
$labels['information'] = "Information";
$labels['Sunday'] = 'Dimanche';
$labels['Monday'] = 'Lundi';
$labels['Tuesday'] = 'Mardi';
$labels['Wednesday'] = 'Mercredi';
$labels['Thursday'] = 'Jeudi';
$labels['Friday'] = 'Vendredi';
$labels['Saturday'] = 'Samedi';

$labels['January'] = 'Janvier';
$labels['February'] = 'Février';
$labels['March'] = 'Mars';
$labels['April'] = 'Avril';
$labels['May'] = 'Mai';
$labels['June'] = 'Juin';
$labels['July'] = 'Juillet';
$labels['August'] = 'Août';
$labels['September'] = 'Septembre';
$labels['October'] = 'Octobre';
$labels['November'] = 'Novembre';
$labels['December'] = 'Décembre';

$labels['date_asc'] = "Ancien au plus récent";
$labels['date_desc'] = "Récent au plus ancien";
$labels['site'] = "Site";
$labels['source'] = "Source";

$labels['tout'] = "A la suite";
$labels['un'] = "Vignette";
$labels['news_mode'] = "Mode des news";
$labels['news_start_nb_rows'] = "Lignes d'informations par défaut";

$labels["small"] = "Petit format";
$labels["large"] = "Grand format";

$labels["right_q"] = "Administrateur et publieur";
$labels["right_a"] = "Administrateur";
$labels["right_p"] = "Publieur";

$labels['publish'] = 'Publier une information';
$labels['publish_flux'] = 'Publier un fil d\'information';
$labels['filter'] = 'Filtrer';
$labels['add'] = 'Ajouter';
$labels['see_more'] = 'Voir plus';

$labels['twitter_navigator_error'] = 'Votre navigateur ne permet pas de récupérer les flux ';
$labels['open_in_new_tab'] = 'Ouvrir dans un nouvel onglet';

$labels['create_publish'] = 'Créer une publication';
$labels['edit'] = 'Modifier';

$labels['choose_service'] = 'Choisissez un service';
$labels['select_service'] = 'Sélectionnez un service';

$labels['choose_title'] = 'Choisissez un titre';
$labels['write_admin_news'] = 'Ecrivez la publication';

$labels['admin_news_title'] = 'Titre de la publication';
$labels['admin_news_placeholder'] = 'Voici les nouvelles....';

$labels['choose_intranet'] = 'Choisir le site Intranet à afficher';
$labels['select_website'] = 'Sélectionner un site';

$labels['delete_confirm'] = 'Cela affectera tout ceux qui voient actuellement cette publication.\r\nÊtes-vous sûr de vouloir continuer ?';
$labels['deleting'] = 'Suppression...';

$labels['action_denied'] = "Vous n'avez pas les droits pour faire cette action !";
$labels['succefuly_published'] = 'Publié avec succès !';

$labels['choose_sub_service'] = 'Choisir un sous-service';
$labels['no_sub_services'] = 'Pas de sous-services pour ce service.';
$labels['validate'] = 'Valider';
$labels['visualize'] = 'Visualiser';
$labels['ask_notify'] = 'Notifier ?';
$labels['adding'] = 'Ajout en cours...';
$labels['error_field_required'] = 'Vous devez renseigner ce champs !';
$labels['required_fields'] = 'Champs obligatoires';
$labels['visualize_admin_news'] = 'Visualisation de la publication';
$labels['information'] = 'Information';
$labels['published_at'] = 'Publier le';
$labels['confirmation'] = 'Confirmer';
$labels['publishing'] = 'Publication...';

$labels['personal_create_title'] = "Quel type d'information ajouter ? (étape 1/2)";
$labels['intranet_website'] = 'Site intranet';
$labels['intranet_websites'] = 'Sites intranet';
$labels['twitter_account'] = 'Compte twitter';
$labels['twitter_accounts'] = 'Comptes twitter';

$labels['small_format'] = 'Petit format';
$labels['large_format'] = 'Grand format';

$labels['intra_edit_alert'] = 'Toutes les vignettes liées à cette adresse seront impactées !';

$labels['personal_add_intranet_title'] = "Ajouter les informations d'un site intranet";
$labels['personal_edit_intranet_title'] = "Modifier les informations d'un site intranet";
$labels['personal_add_twitter_title'] = 'Ajouter un fil Twitter (étape 2/2)';
$labels['personal_edit_twitter_title'] = 'Modifier un fil Twitter';

$labels['enter_twitter_account'] = "Entrez l'identifiant du compte Twitter à afficher";
$labels['enter_twitter_account_placeholder'] = 'NomDuCompte';

$labels['choose_block_format'] = 'Choisir le format du bloc';

$labels['go_to_publisher_mode'] = 'Passer en mode publieur';
$labels['error_invalid_value'] = 'Vous devez mettre une valeur valide !';
$labels['error_invalid_account'] = "Impossible d'atteindre l'utilisateur !";
$labels['error_maj'] = 'Impossible de faire la mise à jours !';

$labels['filter_modal_title'] = 'Que voulez-vous filtrer ?';
$labels['by_type'] = 'Par type';
$labels['by_category'] = 'Par catégorie';
$labels['headlines'] = 'Fils d\'informations';
$labels['your_personal'] = 'Vos ajouts';

$labels['delete_confirmation'] = 'Êtes-vous sûr de vouloir supprimer ce flux ?';
$labels['draw_choice_title'] = 'Que souhaitez-vous faire ?';
$labels['edit_flux'] = 'Modifier le flux';
$labels['delete_flux'] = 'Supprimer le flux';
$labels['delete_flux_warning_all_intra'] = 'Attention, vous allez supprimer toutes les vignettes lié à ce flux, êtes-vous sûr de votre action ?';
$labels['delete_flux_warning'] = 'Attention, vous allez supprimer ce flux, êtes-vous sûr de votre action ?';
$labels['update_news'] = 'Mise à jours des actualités....';
$labels['new_successfuly_updated'] = 'Actualités mises à jours avec succès !';
$labels['error_reorder'] = 'Une erreur est survenue lors du triage ! Êtes-vous connectez à internet ?';

$labels['create_new_comment'] = 'Création d\'un nouveau commentaire';

$labels['edit_article'] = 'Modifier l\'article';
$labels['delete_article'] = 'Supprimer l\'article';
$labels['copy_article'] = 'Copier le lien de l\'article';
$labels['articles'] = 'Articles';
$labels['create_article'] = 'Créer un nouvel article';
$labels['admin_edit_only'] = 'Autoriser uniquement les administrateurs de l\'espace à modifier l\'article';
$labels['enable_comments'] = 'Autoriser la publication de commentaires';
$labels['cancel'] = 'Annuler';
$labels['save'] = 'Sauvegarder';
$labels['add'] = 'Ajouter';
$labels['respond'] = 'Répondre';
$labels['sort_by'] = 'Trier par : ';
$labels['newest'] = 'Plus récents';
$labels['oldest'] = 'Plus anciens';
$labels['more_comments'] = 'Plus de commentaires';
$labels['less_comments'] = 'Moins de commentaires';
$labels['more_reactions'] = 'Plus de réactions';
$labels['less_reactions'] = 'Moins de réactions';
$labels['more_responses'] = 'Plus de réponses';
$labels['display_fav_only'] = 'Afficher uniquement les favoris';
$labels['article_image'] = 'Image de l\'article';
$labels['like_action'] = 'J\'aime';
$labels['dislike_action'] = 'Je n\'aime pas';
$labels['comment_menu'] = 'Menu du commentaire';
$labels['edit_comment'] = 'Modifier le commentaire';
$labels['delete_comment'] = 'Supprimer le commentaire';
$labels['more_options'] = 'Plus d\'options';

// Message
$labels['fav_updated'] = 'Vos articles favoris ont été mis à jour';
$labels['error_editing'] = 'Erreur lors de la modification';
$labels['delete_comment_confirm'] = 'Êtes-vous sûr de vouloir supprimer ce commentaire ?';
$labels['delete_post_success'] = 'Le post a été supprimé avec succès.';
$labels['delete_post_failure'] = 'Erreur lors de la suppression du post.';
$labels['creator_edit_only'] = 'Seul le créateur de cet article peut le modifier.';
$labels['creator_delete_only'] = 'Seul le créateur de cet article peut le supprimer.';
$labels['every_field_required'] = 'Tous les champs sont requis.';
$labels['article_created'] = 'Article créé avec succès.';
$labels['article_created_image_error'] = 'Article créé, mais échec de l\'enregistrement de certaines images.';
$labels['article_creation_error'] = 'Échec de création de l\'article.';
$labels['article_unfindable'] = 'Article introuvable.';
$labels['image_delete_failure'] = 'Echec de suppression de l\'image existante.';
$labels['image_save_failure'] = 'Echec de l\'enregistrement de l\'image: ';
$labels['article_updated'] = 'Article mis à jour avec succès.';
$labels['article_updated_image_error'] = 'Article mis à jour, mais échec de l\'enregistrement de certaines images.';
$labels['article_updated_error'] = 'Échec de mise à jour de l\'article.';
$labels['article_id_required'] = 'L\'identifiant de l\'article est requis.';
$labels['the_article'] = 'L\'article ';
$labels['has_been_deleted'] = ' a été supprimé avec succès.';
// TAG
$labels['tag_created'] = 'Tag créé avec succès.';
$labels['tag_creation_failure'] = 'Echec de création du tag.';
$labels['no_tag_found'] = 'Aucun tag trouvé.';
$labels['tag_name_required'] = 'Le nom du tag est requis.';
$labels['tag_unfindable'] = 'Tag introuvable.';
$labels['tag_delete_error'] = 'Echec de suppression du tag ';
$labels['the_tag'] = 'Le tag ';
$labels['tag_associated_success'] = 'Tag associé au post avec succès.';
$labels['tag_associated_failure'] = 'Echec de l\'association du tag avec le post.';
$labels['tag_unassociated'] = 'Tag dissocié du post avec succès.';
$labels['tag_delete_failure'] = 'Echec de la suppression du tag lié au post.';
// COMMENTS
$labels['comment_field_required'] = 'Le champ commentaire est requis.';
$labels['comment_creation_failed'] = 'Echec de création du commentaire.';
$labels['comment_creation'] = 'Commentaire créé avec succès.';
$labels['response_creation'] = 'Réponse créée avec succès.';
$labels['response_creation_failed'] = 'Echec de création de la réponse.';
$labels['comment_unfindable'] = 'Commentaire introuvable.';
$labels['cannot_edit_comment'] = 'Vous n\'êtes pas autorisé à modifier ce commentaire.';
$labels['cannot_delete_comment'] = 'Vous n\'êtes pas autorisé à supprimer ce commentaire.';
$labels['comment_updated'] = 'Commentaire mis à jour avec succès.';
$labels['comment_updated_failure'] = 'Echec de mise à jour du commentaire.';
$labels['comment_uid_required'] = 'L\'uid du commentaire est requis.';
$labels['comment_deleted'] = 'Le commentaire a été supprimé avec succès.';
$labels['comment_deleted_failure'] = 'Echec de suppression du commentaire.';
$labels['react_to_own_comment'] = 'Vous ne pouvez pas réagir à votre propre commentaire.';
$labels['unlike'] = 'Like annulé avec succès.';
$labels['like_to_dislike'] = 'Like annulé, dislike enregistré avec succès.';
$labels['failed_to_save...'] = 'Échec de l\'enregistrement du ';
$labels['...saved'] = ' enregistré avec succès.';
$labels['undislike'] = 'Dislike annulé avec succès.';
$labels['dislike_to_like'] = 'Dislike annulé, like enregistré avec succès.';
//REACTIONS
$labels['reaction_creation'] = 'Réaction créée avec succès.';
$labels['reaction_creation_failure'] = 'Echec de création de la réaction.';
$labels['reaction_deleted'] = 'La réaction a été supprimée avec succès.';
$labels['reaction_deleted_failure'] = 'Echec de suppression de la réaction.';
$labels['no_reaction_found'] = 'Aucune réaction trouvée.';
//IMAGES
$labels['failed_to_load_image'] = 'Echec du chargement de l\'image.';
