<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/moncompte/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/

$labels = array();

$labels['control'] = "Display messages";

$labels['discussion'] = "Chat";

$labels['search_in'] = 'Search in';
$labels['search_in_all_folders'] = 'Search in all folders';
$labels['search_in_all_contacts'] = 'Search in all contacts';
$labels['search_in_calendars'] = 'Search in calendars';
$labels['search_in_tasks'] = 'Search in tasks';

$labels['showcontactstitle'] = 'Open window to search a contact';

$labels['allcontacts'] = 'All contacts';
$labels['allannuaires'] = 'All adress book';
$labels['personalannuaire'] = 'Personal adress book';
$labels['personalsearchs'] = 'your searches';

$labels['foundin'] = 'found in';

$labels['personalcalendar'] = 'Personal calendar';
$labels['personaladdressbook'] = 'Personal adress book';
$labels['personaltasks'] = 'Personal tasks';

$labels['logo_title'] = 'Go to homepage';
$labels['min_toggle_title'] = 'Change display mode (compact or normal)';
$labels['mail_title'] = 'Open your personal and shared emails';
$labels['agenda_title'] = 'Open your personal and shared calendars';
$labels['contact_title'] = 'Open your personal and shared contacts';
$labels['discussion_title'] = 'Open your instant discussions';
$labels['tasklist_title'] = 'Open your personal and shared tasks';
$labels['settings_title'] = 'Open web portal settings';

$labels['help'] = 'Help';
$labels['settings_themes'] = 'Choose a theme for the interface';
$labels['themes_title_auto'] = 'Automatic';
$labels['themes_description_auto'] = 'The theme color automatically adapts to your system configuration (default behavior).';
$labels['themes_title_light'] = 'Light';
$labels['themes_description_light'] = 'A light theme based on white and light gray colors.';
$labels['themes_title_dark'] = 'Dark';
$labels['themes_description_dark'] = 'A dark theme based on dark gray shades.';
$labels['themes_title_sunset'] = 'Sunset by JP';
$labels['themes_description_sunset'] = 'A dark theme based on gray shades.';
$labels['themes_title_ens'] = 'ENS';
$labels['themes_description_ens'] = 'ENS theme.';