<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/moncompte/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/

$labels = array();

$labels['control'] = "Affichage des messages";

$labels['discussion'] = "Mes discussion";

$labels['search_in'] = 'Rechercher dans';
$labels['search_in_all_folders'] = 'Rechercher dans tous les dossiers';
$labels['search_in_all_contacts'] = 'Rechercher dans tous les contacts';
$labels['search_in_calendars'] = 'Rechercher dans les agendas';
$labels['search_in_tasks'] = 'Rechercher dans les tâches';

$labels['showcontactstitle'] = 'Ouvrir la fenêtre pour chercher un contact';

$labels['allcontacts'] = 'Tous les contacts';
$labels['allannuaires'] = 'Tous les annuaires';
$labels['personalannuaire'] = 'Annuaire personnel et ministériel (Mél)';
$labels['personalsearchs'] = 'Vos recherches enregistrées';

$labels['foundin'] = 'Trouvé dans';

$labels['personalcalendar'] = 'Agenda personnel';
$labels['personaladdressbook'] = 'Carnet personnel';
$labels['personaltasks'] = 'Tâches personnelles';

$labels['logo_title'] = 'Retournez sur la page d\'accueil du portail web';
$labels['min_toggle_title'] = 'Changer le mode d\'affichage du portail web (compact ou normal)';
$labels['mail_title'] = 'Ouvrez vos courriels personnels et vos boites partagées';
$labels['agenda_title'] = 'Ouvrez vos agendas personnels et partagés';
$labels['contact_title'] = 'Ouvrez vos contacts personnels et partagés';
$labels['discussion_title'] = 'Ouvrez vos discussions intantanées';
$labels['tasklist_title'] = 'Ouvrez vos tâches personnelles et partagées';
$labels['settings_title'] = 'Ouvrez les paramètres du portail web';

$labels['help'] = 'Aide';
$labels['settings_themes'] = 'Choix du thème pour l\'interface';
$labels['themes_title_auto'] = 'Automatique';
$labels['themes_description_auto'] = 'La couleur du thème s\'adapte automatiquement à la configuration de votre système (fonctionnement par défaut).';
$labels['themes_title_light'] = 'Clair';
$labels['themes_description_light'] = 'Un thème clair basé sur les couleurs blanc et gris clair.';
$labels['themes_title_dark'] = 'Sombre';
$labels['themes_description_dark'] = 'Un thème sombre basé sur des nuances de gris foncé.';
$labels['themes_title_sunset'] = 'Sunset by JP';
$labels['themes_description_sunset'] = 'Un thème sombre basé sur des nuances de gris.';
