<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/moncompte/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/

$labels = array();

$labels['control'] = "Affichage des messages";

$labels['discussion'] = "Discussion";

$labels['search_in'] = 'Rechercher dans';
$labels['search_in_all_folders'] = 'Rechercher dans tous les dossiers';
$labels['search_in_all_contacts'] = 'Rechercher dans tous les contacts';
$labels['search_in_calendars'] = 'Rechercher dans les agendas';
$labels['search_in_tasks'] = 'Rechercher dans les tâches';

$labels['showcontactstitle'] = 'Ouvrir la fenêtre pour chercher un contact';

$labels['allcontacts'] = 'Tous les contacts';
$labels['allannuaires'] = 'Tous les annuaires';
$labels['personalannuaire'] = 'Annuaire personnel et ministériel (Mél)';

$labels['foundin'] = 'Trouvé dans';

$labels['personalcalendar'] = 'Agenda personnel';
$labels['personaladdressbook'] = 'Carnet personnel';
$labels['personaltasks'] = 'Tâches personnelles';

$labels['help'] = 'Aide';
