<?php
$labels = [];
$labels['erreur_connexion_visio'] = "Impossible de contacter le service de visioconférence pour le moment.";
$labels['event-dinum'] = "Visio";
$labels['join_visio'] = 'Rejoindre la Visio : $name';
$labels['join_visio_new_window'] = 'Rejoindre la Visio : $name (nouvelle fenêtre)';
$labels['join_visio_by_phone'] = "Rejoindre la Visio par téléphone";
$labels['room_label'] = 'Room : $name';
$labels['visio_label'] = 'Visio : $name';
