<?php

$labels = array();
$labels['initials'] = 'Initialen';
$labels['profession'] = 'Berufsbezeichnung';
$labels['officelocation'] = 'Büro Adresse';
$labels['children'] = 'Kinder';
$labels['pgppublickey'] = 'PGP-Schlüssel';
$labels['pkcs7publickey'] = 'S/MIME-Schlüssel';
$labels['freebusyurl'] = 'Frei/Belegt URL';
$labels['typebusiness'] = 'Dienstlich';
$labels['typebusinessfax'] = 'Dienst';
$labels['typecompany'] = 'Firma';
$labels['typeprimary'] = 'Primär';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Funk';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'Telescrit';
$labels['typecallback'] = 'Rückruf';
$labels['settings'] = 'Einstellungen';

$labels['bookcreate'] = 'Adressbuch anlegen';
$labels['bookedit'] = 'Adressbuch bearbeiten';
$labels['bookdelete'] = 'Adressbuch löschen';
$labels['bookproperties'] = 'Eigenschaften des Adressbuchs';
$labels['bookname'] = 'Name des Buches';
$labels['parentbook'] = 'Übergeordnetes Buch';
$labels['bookshowurl'] = 'CardDAV-URL anzeigen';
$labels['carddavurldescription'] = 'Benutzen Sie folgende Addresse in einer <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CalDAV</a>-Anwendung um dieses spezifische Adressbuch mit dem Computer oder Mobiltelefon zu synchronisieren.';

$labels['addressbookprio'] = 'Reihenfolge der Adressbücher';
$labels['personalfirst'] = 'Private(s) Adressbuch/Adressbücher zuerst';
$labels['globalfirst'] = 'Globale(s) Adressbuch/Adressbücher zuerst';
$labels['personalonly'] = 'Nur persönliche(s) Adressbuch/Adressbücher';
$labels['globalonly'] = 'Nur globale(s) Adressbuch/Adressbücher';

$messages['bookdeleteconfirm']  = 'Soll das gewählte Adressbuch und alle Kontakte darin wirklich gelöscht werden?';
$messages['bookdeleting'] = 'Adressbuch wird gelöscht...';
$messages['booksaving'] = 'Adressbuch wird gespeichert...';
$messages['bookdeleted'] = 'Adressbuch erfolgreich gelöscht.';
$messages['bookupdated'] = 'Adressbuch erfolgreich aktualisiert.';
$messages['bookcreated'] = 'Adressbuch erfolgreich angelegt.';
$messages['bookdeleteerror'] = 'Fehler beim Löschen des Adressbuchs.';
$messages['bookupdateerror'] = 'Fehler beim Aktualisieren des Adressbuchs.';
$messages['bookcreateerror'] = 'Fehler beim Anlegen des Adressbuchs.';
$messages['nobooknamewarning'] = 'Bitte den Namen des Adressbuchs angeben.';
$messages['noemailnamewarning'] = 'Bitte E-Mail-Adresse oder Namen des Kontakts angeben.';

?>
