<?php

$labels = array();
$labels['initials'] = 'Initiales';
$labels['profession'] = 'Profession';
$labels['officelocation'] = 'Emplacement du bureau';
$labels['children'] = 'Enfant';
$labels['pgppublickey'] = 'Clé publique PGP';
$labels['pkcs7publickey'] = 'Clé publique S/MIME';
$labels['freebusyurl'] = 'URL Disponible/Occupé';
$labels['typebusiness'] = 'Travail';
$labels['typebusinessfax'] = 'Fax Travail';
$labels['typecompany'] = 'Société';
$labels['typeprimary'] = 'Principal';
$labels['typetelex'] = 'Télex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Rappel';
$labels['settings'] = 'Paramètres';

$labels['categories'] = 'Catégories';
$labels['members'] = 'Membres';
$labels['room'] = 'Bureau';

$labels['bookcreate'] = 'Créer un carnet d\'adresse';
$labels['bookedit'] = 'Modifier le carnet d\'adresse';
$labels['bookdelete'] = 'Supprimer le carnet d\'adresse';
$labels['bookproperties'] = 'Propriétés du carnet d\'adresse';
$labels['bookname'] = 'Nom du carnet';
$labels['parentbook'] = 'Carnet parent';

$labels['manageresources'] = 'Gérer les carnets d\'adresses';

$labels['tabsharing'] = 'Partage';
// PAMELA
$labels['tabsharinggroup'] = 'Partage à un groupe';
$labels['favorites'] = 'Favoris';

$labels['addressbookprio'] = 'Sélection du(des) carnet(s) d\'adresses/comportement';
$labels['personalfirst'] = 'Carnet(s) d\'adresse personnel en premier';
$labels['globalfirst'] = 'Carnet(s) d\'adresse global(aux) en premier';
$labels['personalonly'] = 'Carnet(s) d\'adresse personnel seulement';
$labels['globalonly'] = 'Carnet(s) d\'adresse global(aux) seulement';

$messages['bookdeleteconfirm']  = 'Voulez-vous vraiment supprimer le carnet d\'adresse sélectionné et tous ses contacts?';
$messages['bookdeleting'] = 'Suppression du carnet d\'adresse...';
$messages['booksaving'] = 'Enregistrement du carnet d\'adresse...';
$messages['bookdeleted'] = 'Carnet d\'adresse supprimé.';
$messages['bookupdated'] = 'Carnet d\'adresse modifié.';
$messages['bookcreated'] = 'Carnet d\'adresse créé.';
$messages['bookdeleteerror'] = 'Une erreur est survenue lors de la suppression du carnet d\'adresse.';
$messages['bookupdateerror'] = 'Une erreur est survenue lors de la modification du carnet d\'adresse.';
$messages['bookcreateerror'] = 'Une erreur est survenue lors de la création du carnet d\'adresse.';
$messages['nobooknamewarning'] = 'Merci de saisir un nom pour le carnet d\'adresse';
$messages['noemailnamewarning'] = 'Merci de saisir une adresse de courriel ou un nom de contact.';

?>
