<?php

$labels = array();
$labels['initials'] = 'Initialen';
$labels['profession'] = 'Beroep';
$labels['officelocation'] = 'Kantoorlocatie';
$labels['children'] = 'Kinderen';
$labels['pgppublickey'] = 'PGP publieke sleutel';
$labels['pkcs7publickey'] = 'S/MIME publieke sleutel';
$labels['freebusyurl'] = 'Free/Busy URL';
$labels['typebusiness'] = 'Zakelijk';
$labels['typebusinessfax'] = 'Zakelijk (Fax)';
$labels['typecompany'] = 'Bedrijfsnaam';
$labels['typeprimary'] = 'Primair';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Callback';
$labels['settings'] = 'Instellingen';

$labels['bookcreate'] = 'Maak adresboek aan';
$labels['bookedit'] = 'Wijzig adresboek';
$labels['bookdelete'] = 'Adresboek verwijderen';
$labels['bookproperties'] = 'Eigenschappen voor adresboek';
$labels['bookname'] = 'Adresboek naam';
$labels['parentbook'] = 'Toevoegen aan bestaand adresboek';

$labels['addressbookprio'] = 'Gedrag voor adresboek(en)-selectie';
$labels['personalfirst'] = 'Eerst persoonlijke adresboek(en)';
$labels['globalfirst'] = 'Eerst globale adresboek(en)';
$labels['personalonly'] = 'Alleen persoonlijke adresboek(en)';
$labels['globalonly'] = 'Alleen globale adresboek(en)';

$messages['bookdeleteconfirm']  = 'Weet u zeker dat u het geselecteerde adresboek inclusief inhoud wilt verwijderen?';
$messages['bookdeleting'] = 'Adresboek aan het verwijderen...';
$messages['booksaving'] = 'Adresboek aan het opslaan...';
$messages['bookdeleted'] = 'Adresboek succesvol verwijderd.';
$messages['bookupdated'] = 'Adresboek succesvol gewijzigd.';
$messages['bookcreated'] = 'Adresboek succesvol aangemaakt.';
$messages['bookdeleteerror'] = 'Er heeft zich een fout voorgedaan bij het verwijderen van het adresboek.';
$messages['bookupdateerror'] = 'Er heeft zich een fout voorgedaan bij het wijzigen van het adresboek.';
$messages['bookcreateerror'] = 'Er heeft zich een fout voorgedaan bij het aanmaken van het adresboek.';
$messages['nobooknamewarning'] = 'Please, enter address book name.';
$messages['noemailnamewarning'] = 'Please, enter email address or contact name.';

?>
