<?php

$labels = array();
$labels['initials'] = 'Inicjały';
$labels['profession'] = 'Zawód';
$labels['officelocation'] = 'Adres biura';
$labels['children'] = 'Dzieci';
$labels['pgppublickey'] = 'Klucz publ. PGP';
$labels['freebusyurl'] = 'URL Free-busy';
$labels['settings'] = 'Ustawienia';

$labels['typebusiness'] = 'Praca';
$labels['typebusinessfax'] = 'Fax firmowy';
$labels['typecallback'] = 'Callback';
$labels['typecompany'] = 'Firma';
$labels['typeprimary'] = 'Główny';
$labels['typetelex'] = 'Teleks';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';

$labels['addressbookprio'] = 'Wybór/zachowanie książek adresowych';
$labels['personalfirst'] = 'Najpierw osobiste książki adresowe';
$labels['globalfirst'] = 'Najpierw globalne książki adresowe';
$labels['personalonly'] = 'Tylko osobiste książki adresowe';
$labels['globalonly'] = 'Tylko globalne książki adresowe';

$labels['bookcreate'] = 'Utwórz książkę';
$labels['bookedit'] = 'Edytuj książkę';
$labels['bookdelete'] = 'Usuń książkę';
$labels['bookproperties'] = 'Właściwości książki adresowej';
$labels['bookname'] = 'Nazwa książki';
$labels['parentbook'] = 'Książka nadrzędna';

$messages['bookdeleteconfirm'] = 'Czy na pewno chcesz usunąć wybraną książkę i wszystkie kontakty w niej zapisane?';
$messages['bookdeleting'] = 'Usuwanie książki adresowej...';
$messages['booksaving'] = 'Zapisywanie książki adresowej...';
$messages['bookdeleted'] = 'Książka adresowa została usunięta.';
$messages['bookupdated'] = 'Książka adresowa została zaktualizowana.';
$messages['bookcreated'] = 'Książka adresowa została utworzona.';
$messages['bookdeleteerror'] = 'Wystąpił błąd podczas usuwania książki adresowej.';
$messages['bookupdateerror'] = 'Wystąpił błąd podczas zmiany książki adresowej.';
$messages['bookcreateerror'] = 'Wystąpił błąd podczas tworzenia książki adresowej.';
$messages['nobooknamewarning'] = 'Proszę podać nazwę książki adresowej.';
$messages['noemailnamewarning'] = 'Proszę podać adres email lub nazwę kontaktu.';

?>
