<?php
/*

+-----------------------------------------------------------------------+
| plugins/kolab_addressbook/localization/ru_RU.inc                      |
|                                                                       |
| Russian translation for roundcube/kolab_addressbook plugin            |
| Copyright (C) 2008-2011                                               |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Sergey Dukachev <iam@dukess.ru>                               |
| Updates:                                                              |
+-----------------------------------------------------------------------+

@version 2011-05-11

*/

$labels = array();
$labels['initials'] = 'Инициалы';
$labels['profession'] = 'Профессия';
$labels['officelocation'] = 'Адрес офиса';
$labels['children'] = 'Дети';
$labels['pgppublickey'] = 'Публичный ключ PGP';
$labels['freebusyurl'] = 'URL свободен/занят';
$labels['settings'] = 'Настройки';

?>