<?php
$labels['calendlink'] = 'Lien vers la prise de rendez-vous';
$labels['calendlink-label'] = 'Pour prendre rendez-vous : cliquez ici';
$labels['event_limit'] = 'Nombres maximum d\'évènements affichés';
$labels['event-is-recur'] = 'Attention, vous allez copier la série complète de la récurrence, la copie d\'une seule occurrence n\'est pas possible.\nVoulez-vous quand même continuer ?';
$labels['event-get-error'] = 'Erreur lors de la récupération de l\'événement maître';
$labels['event-not-recur-error'] = 'L\'évènement sélectionné n\'est pas une exception ou récurrent.';